[#4630] keactrl options tests

diff --git a/src/bin/keactrl/tests/keactrl_tests.sh.in b/src/bin/keactrl/tests/keactrl_tests.sh.in
--- a/src/bin/keactrl/tests/keactrl_tests.sh.in
+++ b/src/bin/keactrl/tests/keactrl_tests.sh.in
@@ -1426,6 +1426,158 @@ bin_path=$(dirname "${keactrl}")
 version_test 'keactrl.version' 'long_version_too_please'
 }
 
+# Kea servers have to be stopped when the test finishes to avoid timeout.
+shutdown_servers() {
+    # Use keactrl stop to shutdown the servers.
+    printf 'Stopping Kea: %s stop -c %s\n' "${keactrl}" "${KEACTRL_CFG_FILE}"
+    set +e
+    "${keactrl}" stop -c "${KEACTRL_CFG_FILE}"
+    assert_eq 0 "${?}" "Expected keactrl to return %d, returned value was %d."
+    set -e
+    wait_for_server_down 5 "${wildcard_name}"
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
+        "Expected wait_for_server_down return %d, returned %d"
+}
+
+server_options_tests() {
+    test_start "keactrl.server_options_config_file_test"
+    # Test checking that the DHCPv4 and DHCPv6 servers are started with the expected arguments.
+    # First test with the -F argument in the config file.
+
+    # Create configuration file for keactrl. This configuration enables
+    # DHCPv4, DHCPv6, D2 and netconf.
+    keactrl_config="${CFG_FILES}\ndhcp4=yes\ndhcp6=yes\n\
+dhcp_ddns=no\nnetconf=no\n\
+kea_verbose=no\n\
+dhcp4_cli_options=\"-F\"\n\
+dhcp6_cli_options=\"-F\"\n${keactrl_fixed_config}"
+
+    # Create configuration file for Kea and for keactrl.
+    create_dhcp4_config "${dhcp4_config}"
+    create_dhcp6_config "${dhcp6_config}"
+    create_d2_config "${dhcp_ddns_config}"
+    create_nc_config "${netconf_config}"
+    create_keactrl_config "${keactrl_config}"
+
+    # Set logging to a file.
+    set_logger
+
+    # Start servers using keactrl script.
+    printf 'INFO/test_lib: Starting Kea: %s start -c %s -s dhcp4,dhcp6\n' \
+           "${keactrl}" "${KEACTRL_CFG_FILE}"
+    set +e
+    "${keactrl}" start -c "${KEACTRL_CFG_FILE}" -s dhcp4,dhcp6
+    assert_eq 0 "${?}" "Expected keactrl to return %d, returned value was %d"
+    set -e
+
+    # Wait up to 20s for the DHCPv6 server to configure.
+    wait_for_message 20 "DHCP6_CONFIG_COMPLETE" 1
+    assert_eq 1 "${_WAIT_FOR_MESSAGE}" \
+        "Timeout waiting for ${kea6_name} to start. \
+Expected wait_for_message return %d, returned %d."
+
+    # Wait up to 20s for the DHCPv4 server to configure.
+    wait_for_message 20 "DHCP4_CONFIG_COMPLETE" 1
+    assert_eq 1 "${_WAIT_FOR_MESSAGE}" \
+        "Timeout waiting for ${kea4_name} to start. \
+Expected wait_for_message return %d, returned %d."
+
+    # Make sure that all servers are running and started with expected arguments.
+    # DHCPv4 server
+    get_pid "${kea4_name}" "${DHCP4_CFG_FILE_NAME}"
+    assert_eq 1 "${_GET_PIDS_NUM}" \
+        "ERROR: Expected %d ${kea4_name} process running, found %d processes running"
+
+    DHCP4_CMDLINE="$(ps -p "${_GET_PID}" -o args=)"
+    if ! echo "${DHCP4_CMDLINE}" | grep -q -- ' -F'; then
+        printf "ERROR: kea-dhcp4 did not start with expected -F argument.\n"
+        shutdown_servers
+        test_finish 1
+    fi
+
+    get_pid "${kea6_name}" "${DHCP6_CFG_FILE_NAME}"
+    assert_eq 1 "${_GET_PIDS_NUM}" \
+        "ERROR: Expected %d ${kea6_name} process running, found %d processes running"
+
+    DHCP6_CMDLINE="$(ps -p "${_GET_PID}" -o args=)"
+    if ! echo "${DHCP6_CMDLINE}" | grep -q -- ' -F'; then
+        printf "ERROR: kea-dhcp6 did not start with expected -F argument.\n"
+        shutdown_servers
+        test_finish 1
+    fi
+
+    shutdown_servers
+    test_finish 0
+
+    test_start "keactrl.server_options_command_line_test"
+    # Second test with the -X argument in the command line and -F in the config file.
+
+    # Create configuration file for keactrl. This configuration enables
+    # DHCPv4, DHCPv6, D2 and netconf.
+    keactrl_config="${CFG_FILES}\ndhcp4=yes\ndhcp6=yes\n\
+dhcp_ddns=no\nnetconf=no\n\
+kea_verbose=no\n\
+dhcp4_cli_options=\"-F\"\n\
+dhcp6_cli_options=\"-F\"\n${keactrl_fixed_config}"
+
+    # Create configuration file for Kea and for keactrl.
+    create_dhcp4_config "${dhcp4_config}"
+    create_dhcp6_config "${dhcp6_config}"
+    create_d2_config "${dhcp_ddns_config}"
+    create_nc_config "${netconf_config}"
+    create_keactrl_config "${keactrl_config}"
+
+    # Set logging to a file.
+    set_logger
+
+    # Start servers using keactrl script.
+    printf 'INFO/test_lib: Starting Kea: %s start -c %s -s dhcp4,dhcp6 -- -X\n' \
+           "${keactrl}" "${KEACTRL_CFG_FILE}"
+    set +e
+    "${keactrl}" start -c "${KEACTRL_CFG_FILE}" -s dhcp4,dhcp6 -- -X
+    assert_eq 0 "${?}" "Expected keactrl to return %d, returned value was %d"
+    set -e
+
+    # Wait up to 20s for the DHCPv6 server to configure.
+    wait_for_message 20 "DHCP6_CONFIG_COMPLETE" 1
+    assert_eq 1 "${_WAIT_FOR_MESSAGE}" \
+        "Timeout waiting for ${kea6_name} to start. \
+Expected wait_for_message return %d, returned %d."
+
+    # Wait up to 20s for the DHCPv4 server to configure.
+    wait_for_message 20 "DHCP4_CONFIG_COMPLETE" 1
+    assert_eq 1 "${_WAIT_FOR_MESSAGE}" \
+        "Timeout waiting for ${kea4_name} to start. \
+Expected wait_for_message return %d, returned %d."
+
+    # Make sure that all servers are running and started with expected arguments.
+    # DHCPv4 server
+    get_pid "${kea4_name}" "${DHCP4_CFG_FILE_NAME}"
+    assert_eq 1 "${_GET_PIDS_NUM}" \
+        "ERROR: Expected %d ${kea4_name} process running, found %d processes running"
+
+    DHCP4_CMDLINE="$(ps -p "${_GET_PID}" -o args=)"
+    if ! echo "${DHCP4_CMDLINE}" | grep -q -- ' -X -F'; then
+        printf "ERROR: kea-dhcp4 did not start with expected -X -F argument.\n"
+        shutdown_servers
+        test_finish 1
+    fi
+
+    get_pid "${kea6_name}" "${DHCP6_CFG_FILE_NAME}"
+    assert_eq 1 "${_GET_PIDS_NUM}" \
+        "ERROR: Expected %d ${kea6_name} process running, found %d processes running"
+
+    DHCP6_CMDLINE="$(ps -p "${_GET_PID}" -o args=)"
+    if ! echo "${DHCP6_CMDLINE}" | grep -q -- ' -X -F'; then
+        printf "ERROR: kea-dhcp6 did not start with expected -X -F argument.\n"
+        shutdown_servers
+        test_finish 1
+    fi
+
+    shutdown_servers
+    test_finish 0
+}
+
 keactrl_status_tests
 version_command_test
 start_all_servers_no_verbose_test
@@ -1437,3 +1589,4 @@ late_start_v6_server_test
 stop_selected_server_test
 status_no_config_test
 keactrl_error_reporting_tests
+server_options_tests
