change requests from isc
# Conflicts:
#	src/bin/admin/tests/data/pgsql.lease6_dump_test.reference.csv

diff --git a/src/bin/admin/kea-admin.in b/src/bin/admin/kea-admin.in
--- a/src/bin/admin/kea-admin.in
+++ b/src/bin/admin/kea-admin.in
@@ -208,7 +208,8 @@ cql_init() {
         printf "Creating and initializing tables using script %s...\n" $scripts_dir/cql/dhcpdb_create.cql
         cql_execute_script $scripts_dir/cql/dhcpdb_create.cql
     else
-        printf "Tables are already created.\n"
+        log_error "Expected empty database $db_name, but the following tables are present \n$result. Aborting."
+        exit 2
     fi
 
     version=`cql_version`
@@ -485,44 +486,38 @@ cql_dump() {
 
     # Fetch the correct SQL text. Note this function will exit
     # if it fails.
-    get_dump_query $version
+
+    select_where_clause=""
+    if [ $dump_type -eq 4 ]; then
+        dump_qry="SELECT address,hwaddr,client_id,valid_lifetime,expire,subnet_id,fqdn_fwd,fqdn_rev,hostname,state FROM keatest.lease4"
+        select_where_clause=" WHERE address = 0" # invalid address
+    elif [ $dump_type -eq 6 ]; then
+        dump_qry="SELECT address,duid,valid_lifetime,expire,subnet_id,pref_lifetime,lease_type,iaid,prefix_len,fqdn_fwd,fqdn_rev,hostname,hwaddr,hwtype,hwaddr_source,state FROM keatest.lease6"
+        select_where_clause=" WHERE address = ::" # invalid address
+    fi
 
     # Make sure they specified a file
     if [ "$dump_file" = "" ]; then
         log_error "you must specify an output file for lease-dump"
         usage
         exit 1
-
     fi
 
     # If output file exists, notify user, allow them a chance to bail
     check_file_overwrite $dump_file
 
-    # Check the temp file too
-    tmp_file="$dump_file.tmp"
-    check_file_overwrite $tmp_file
-
-    # Run the sql to output tab-delimited lease data to a temp file.
-    # By using a temp file we can check for MySQL errors before using
-    # 'tr' to translate tabs to commas.  We do not use MySQL's output
-    # to file as that requires linux superuser privileges to execute
-    # the select.
-    cql_execute "${dump_qry}" > $tmp_file
-    retcode=$?
-    if [ $retcode -ne 0 ]; then
+    cql_execute "${dump_qry}${select_where_clause}" | head -n 2 | tail -n 1 | sed -e 's/\s*//g' | sed -e 's/|/,/g' > $dump_file
+    if [ $? -ne 0 ]; then
         log_error "lease-dump: cql_execute failed, exit code $retcode";
         exit 1
     fi
 
-    # Now translate tabs to commas.
-    cat $tmp_file | tr '\t' ',' >$dump_file
+    cql_execute "${dump_qry}" | tail -n +4 | head -n -2 | sed -e 's/\s*//g' | sed -e 's/|/,/g' | sort -r >> $dump_file
     if [ $? -ne 0 ]; then
-        log_error "lease-dump: reformatting failed";
+        log_error "lease-dump: cql_execute failed, exit code $retcode";
         exit 1
     fi
 
-    # delete the tmp file on success
-    rm $tmp_file
     echo lease$dump_type successfully dumped to $dump_file
     exit 0
 }
diff --git a/src/bin/admin/tests/cql_tests.sh.in b/src/bin/admin/tests/cql_tests.sh.in
--- a/src/bin/admin/tests/cql_tests.sh.in
+++ b/src/bin/admin/tests/cql_tests.sh.in
@@ -22,7 +22,7 @@ db_name="keatest"
 # Set location of the kea-admin.
 keaadmin=@abs_top_builddir@/src/bin/admin/kea-admin
 
-cql_init_test() {
+cql_lease_init_test() {
     test_start "cql.init"
 
     # Wipe the database.
@@ -56,7 +56,7 @@ cql_init_test() {
     cql_execute "SELECT state, name FROM lease_state;"
     assert_eq 0 $? "lease_state table check failed, expected exit code: %d, actual: %d"
 
-    # Trying to create it again should fail.  This verifies the db present
+    # Trying to create it again should fail. This verifies the db present
     # check
     echo ""
     echo "Making sure keyspace creation fails the second time..."
@@ -70,18 +70,18 @@ cql_init_test() {
     test_finish 0
 }
 
-cql_version_test() {
+cql_lease_version_test() {
     test_start "cql.version"
 
     # Wipe the database.
     cql_execute_script $db_scripts_dir/cql/dhcpdb_drop.cql
     assert_eq 0 $? "drop table query failed, exit code %d, expected %d"
 
-    # Create the database
+    # Create the database.
     $keaadmin lease-init cql -u $db_user -p $db_password -n $db_name -d $db_scripts_dir
     assert_eq 0 $? "kea-admin lease-init cql failed, expected exit code: %d, actual: %d"
 
-    # Verfiy that kea-admin lease-version returns the correct version
+    # Verfiy that kea-admin lease-version returns the correct version.
     version=$($keaadmin lease-version cql -u $db_user -p $db_password -n $db_name)
     assert_str_eq "1.0" $version "Expected kea-admin to return %s, returned value was %s"
 
@@ -113,6 +113,154 @@ cql_upgrade_test() {
     test_finish 0
 }
 
-cql_init_test
-cql_version_test
+cql_lease4_dump_test() {
+    test_start "cql.lease4_dump_test"
+
+    test_dir="@abs_top_srcdir@/src/bin/admin/tests"
+    output_dir="@abs_top_builddir@/src/bin/admin/tests"
+    script_dir="@abs_top_srcdir@/src/bin/admin/scripts"
+
+    output_file="$output_dir/data/cql.lease4_dump_test.output.csv"
+    tmp_file="$output_file.tmp"
+
+    ref_file="$test_dir/data/cql.lease4_dump_test.reference.csv"
+
+    # Wipe out any residuals from prior failed runs.
+    if [ -e $output_file ]
+    then
+        rm $output_file
+    fi
+
+    if [ -e $tmp_file ]
+    then
+        rm $tmp_file
+    fi
+
+    # Wipe the database.
+    cql_execute_script $db_scripts_dir/cql/dhcpdb_drop.cql
+    assert_eq 0 $? "drop table query failed, exit code %d, expected %d"
+
+    # Create the database
+    $keaadmin lease-init cql -u $db_user -p $db_password -n $db_name -d $db_scripts_dir
+    assert_eq 0 $? "kea-admin lease-init cql failed, expected exit code: %d, actual: %d"
+
+    # Insert the reference record.
+    # -1073741302 corresponds to 192.0.2.10
+    # -1073741301 corresponds to 192.0.2.11
+    # -1073741300 corresponds to 192.0.2.12
+    # 1430694930 corresponds to 2015-04-04 01:15:30
+    # 1433464245 corresponds to 2015-05-05 02:30:45
+    # 1436173267 corresponds to 2015-06-06 11:01:07
+    insert_sql="\
+insert into lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
+ fqdn_fwd, fqdn_rev, hostname, state)\
+ values(-1073741302,textAsBlob('20'),textAsBlob('30'),40,1430694930,50,true,true,\
+ 'one.example.com', 0);\
+insert into lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
+ fqdn_fwd, fqdn_rev, hostname, state)\
+ values(-1073741301,NULL,textAsBlob('123'),40,1433464245,50,true,true,'', 1);\
+insert into lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
+ fqdn_fwd, fqdn_rev, hostname, state)\
+ values(-1073741300,textAsBlob('22'),NULL,40,1436173267,50,true,true,\
+ 'three.example.com', 2);"
+
+    cql_execute "$insert_sql"
+    assert_eq 0 $? "insert into lease4 failed, expected exit code %d, actual %d"
+
+    # Dump lease4 to output_file.
+    $keaadmin lease-dump cql -4 -u $db_user -p $db_password -n $db_name -d $db_scripts_dir -o $output_file
+    assert_eq 0 $? "kea-admin lease-dump -4 failed, expected exit code %d, actual %d"
+
+    # Compare the dump output to reference file, they should be identical.
+    cmp -s $output_file  $ref_file
+    assert_eq 0 $? "dump file does not match reference file, expected exit code %d, actual %d"
+
+    # remove the output file.
+    rm $output_file
+
+    # Wipe the database.
+    cql_execute_script $db_scripts_dir/cql/dhcpdb_drop.cql
+    assert_eq 0 $? "drop table query failed, exit code %d, expected %d"
+
+    test_finish 0
+}
+
+cql_lease6_dump_test() {
+    test_start "cql.lease6_dump_test"
+
+    test_dir="@abs_top_srcdir@/src/bin/admin/tests"
+    output_dir="@abs_top_builddir@/src/bin/admin/tests"
+    script_dir="@abs_top_srcdir@/src/bin/admin/scripts"
+
+    output_file="$output_dir/data/cql.lease6_dump_test.output.csv"
+    tmp_file="$output_file.tmp"
+
+    ref_file="$test_dir/data/cql.lease6_dump_test.reference.csv"
+
+    # Wipe out any residuals from prior failed runs.
+    if [ -e $output_file ]
+    then
+        rm $output_file
+    fi
+
+    if [ -e $tmp_file ]
+    then
+        rm $tmp_file
+    fi
+
+    # Wipe the database.
+    cql_execute_script $db_scripts_dir/cql/dhcpdb_drop.cql
+    assert_eq 0 $? "drop table query failed, exit code %d, expected %d"
+
+    # Create the database.
+    $keaadmin lease-init cql -u $db_user -p $db_password -n $db_name -d $db_scripts_dir
+    assert_eq 0 $? "could not create database, expected exit code %d, actual %d"
+
+    # Insert the reference record.
+    # 1430694930 corresponds to 2015-04-04 01:15:30
+    # 1433464245 corresponds to 2015-05-05 02:30:45
+    # 1436173267 corresponds to 2015-06-06 11:01:07
+    insert_sql="\
+insert into lease6(address, duid, valid_lifetime, expire, subnet_id,\
+ pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
+ hwaddr, hwtype, hwaddr_source, state)\
+ values('2001:db8::10',textAsBlob('20'),30,1430694930,40,50,1,60,70,true,true,\
+ 'one.example.com',textAsBlob('80'),90,16,0);\
+insert into lease6(address, duid, valid_lifetime, expire, subnet_id,\
+ pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
+ hwaddr, hwtype, hwaddr_source, state)\
+ values('2001:db8::11',NULL,30,1433464245,40,50,1,60,70,true,true,\
+ '',textAsBlob('80'),90,1,1);\
+insert into lease6(address, duid, valid_lifetime, expire, subnet_id,\
+ pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
+ hwaddr, hwtype, hwaddr_source, state)\
+ values('2001:db8::12',textAsBlob('21'),30,1436173267,40,50,1,60,70,true,true,\
+ 'three.example.com',textAsBlob('80'),90,4,2);"
+
+    cql_execute "$insert_sql"
+    assert_eq 0 $? "insert into lease6 failed, expected exit code %d, actual %d"
+
+    # Dump lease4 to output_file.
+    $keaadmin lease-dump cql -6 -u $db_user -p $db_password -n $db_name -d $db_scripts_dir -o $output_file
+    assert_eq 0 $? "kea-admin lease-dump -6 failed, status code %d"
+
+    # Compare the dump output to reference file, they should be identical.
+    cmp -s $output_file  $ref_file
+    assert_eq 0 $? "dump file does not match reference file, expected exit code %d, actual %d"
+
+    # remove the output file.
+    rm $output_file
+
+    # Wipe the database.
+    cql_execute_script $db_scripts_dir/cql/dhcpdb_drop.cql
+    assert_eq 0 $? "drop table query failed, exit code %d, expected %d"
+
+    test_finish 0
+}
+
+# Run tests.
+cql_lease_init_test
+cql_lease_version_test
 cql_upgrade_test
+cql_lease4_dump_test
+cql_lease6_dump_test
