[3916] Use stored functions for Postgres lease dumps
lease_dump_1.0.sh - deleted, now obsolete

src/bin/admin/scripts/pgsql/Makefile.am
    removed entries for lease_dump_1.0.sh

src/bin/admin/kea-admin.in
    get_dump_query() - modified SQL text returned for Postgres backend
    which calls stored functions to produce lease dumps  rather than
    SQL texti from lease_dump_<version>.sh

src/bin/admin/scripts/pgsql/dhcpdb_create.pgsql
    added statments to create lease dump functions:
        lease4DumpHeader
        lease4DumpData
        lease6DumpHeader
        lease6DumpData

src/bin/admin/tests/data/pgsql.lease6_dump_test.reference.csv
    Booleans were expected be 't' or 'f', changed to int 1 or 0

diff --git a/src/bin/admin/kea-admin.in b/src/bin/admin/kea-admin.in
--- a/src/bin/admin/kea-admin.in
+++ b/src/bin/admin/kea-admin.in
@@ -311,36 +311,61 @@ check_file_overwrite () {
 # and protocol
 get_dump_query() {
     local version=$1
+    local dump_sql_file="$scripts_dir/${backend}/lease_dump_$version.sh"
 
     dump_qry=""
-    dump_sql_file="$scripts_dir/${backend}/lease_dump_$version.sh"
-    if [ ! -e $dump_sql_file ]
-    then
-        log_error "lease-dump: cannot access dump_sql_file: $dump_sql_file"
-        exit 1;
-    fi
+    case ${backend} in
+    mysql)
+        if [ ! -e $dump_sql_file ]
+        then
+            log_error "lease-dump: cannot access dump_sql_file: $dump_sql_file"
+            exit 1;
+        fi
 
-    # source in the dump file which defines the sql text we'll need
-    . $dump_sql_file
-    if [ $? -ne 0 ]
-    then
-        log_error "lease-dump: error sourcing dump_sql_file: $dump_sql_file"
-        exit 1
-    fi
+        # source in the dump file which defines the sql text we'll need
+        . $dump_sql_file
+        if [ $? -ne 0 ]
+        then
+            log_error "lease-dump: error sourcing dump_sql_file: $dump_sql_file"
+            exit 1
+        fi
+        # Construct the SQL text to dump the leases based on protocol type
+        case ${dump_type} in
+            4)
+                dump_qry="$lease4_dump_sql";
+                ;;
+            6)
+                dump_qry="$lease6_dump_sql";
+                ;;
+            *)
+                log_error "you must specify -4 or -6 for lease-dump"
+                usage
+                exit 1
+                ;;
+        esac
+        ;;
 
-    # Construct the SQL text to dump the leases based on protocol type
-    case ${dump_type} in
+    pgsql)
+        # Construct the SQL text to dump the leases based on protocol type
+        case ${dump_type} in
         4)
-            dump_qry="$lease4_dump_sql";
+            dump_qry="select * from lease4DumpHeader();select * from lease4DumpData()";
             ;;
         6)
-            dump_qry="$lease6_dump_sql";
+            dump_qry="select * from lease6DumpHeader();select * from lease6DumpData()";
             ;;
         *)
             log_error "you must specify -4 or -6 for lease-dump"
             usage
             exit 1
             ;;
+        esac
+        ;;
+    *)
+        log_error "unsupported backend ${backend}"
+        usage
+        exit 1
+        ;;
     esac
 
     if [ "$dump_qry" = "" ]
