[#1638] wait for process to stop after kill

diff --git a/src/lib/testutils/dhcp_test_lib.sh.in b/src/lib/testutils/dhcp_test_lib.sh.in
--- a/src/lib/testutils/dhcp_test_lib.sh.in
+++ b/src/lib/testutils/dhcp_test_lib.sh.in
@@ -458,8 +458,8 @@ get_process_name() {
 # Wait for file to be created.
 wait_for_file() {
     local file=${1}
-    timeout='4' # seconds
-    deadline=$(($(date +%s) + timeout))
+    local timeout='4' # seconds
+    local deadline=$(($(date +%s) + timeout))
     while ! test -f "${file}"; do
         if test "${deadline}" -lt "$(date +%s)"; then
             # Time is up.
@@ -472,17 +472,17 @@ wait_for_file() {
 }
 
 # Wait for process identified by PID to die.
-wait_for_process_to_die() {
+wait_for_process_to_stop() {
     local pid=${1}
-    timeout='4' # seconds
-    deadline=$(($(date +%s) + timeout))
+    local timeout='4' # seconds
+    local deadline=$(($(date +%s) + timeout))
     while ps "${pid}" >/dev/null; do
         if test "${deadline}" -lt "$(date +%s)"; then
             # Time is up.
-            printf 'ERROR: %s does not want to die.\n' "$(get_process_name "${pid}")" >&2
+            printf 'ERROR: %s is not stopping.\n' "$(get_process_name "${pid}")" >&2
             return 1
         fi
-        printf 'Waiting for %s to die...\n' "$(get_process_name "${pid}")"
+        printf 'Waiting for %s to stop...\n' "$(get_process_name "${pid}")"
         sleep 1
     done
 }
@@ -501,9 +501,10 @@ wait_for_process_to_die() {
 kill_processes_by_name() {
     local proc_name=${1} # Process name
     if [ -z "${proc_name}" ]; then
-        test_lib_error "get_pids requires process name"
+        test_lib_error "kill_processes_by_name requires process name"
         clean_exit 1
     fi
+
     # Obtain PIDs of running processes.
     local pids
     pids=$(pgrep "${proc_name}" || true)
@@ -511,6 +512,12 @@ kill_processes_by_name() {
     for pid in ${pids}; do
         printf 'Shutting down Kea process %s with PID %d...\n' "${proc_name}" "${pid}"
         kill -9 "${pid}" || true
+    done
+
+    # Wait for all processes to stop.
+    for pid in ${pids}; do
+        printf 'Waiting for Kea process %s with PID %d to stop...\n' "${proc_name}" "${pid}"
+        wait_for_process_to_stop "${pid}"
     done
 }
 
