[#4580] Check that variables are populated in upgrade scripts
So instead of:

Processing share/kea/scripts/mysql/upgrade_009.6_to_010.0.sh file...
share/kea/scripts/mysql/upgrade_009.6_to_010.0.sh: line 68: [: : integer expected
<continues as if nothing happened>

You get:

Processing share/kea/scripts/mysql/upgrade_009.6_to_010.0.sh file...
Could not determine tag length in schema '-N', table 'dhcp4_server'.
EXIT 255

diff --git a/src/share/database/scripts/mysql/upgrade_008.1_to_008.2.sh.in b/src/share/database/scripts/mysql/upgrade_008.1_to_008.2.sh.in
--- a/src/share/database/scripts/mysql/upgrade_008.1_to_008.2.sh.in
+++ b/src/share/database/scripts/mysql/upgrade_008.1_to_008.2.sh.in
@@ -58,8 +58,7 @@ for arg in "${@}"; do
 done
 
 # Make sure we can id the schema
-if [ -z "$schema" ]
-then
+if [ -z "${schema-}" ]; then
     printf "Could not find database schema name in cmd line args: %s\n" "${*}"
     exit 255
 fi
@@ -78,6 +77,11 @@ change_column() {
     if ! count=$(mysql -N -B "${@}" -e "${sql}")
     then
         printf 'change_column: schema query failed [%s]\n' "${sql}"
+        exit 255
+    fi
+
+    if [ -z "${count-}" ]; then
+        printf "Could not determine number of records in schema '%s', table '%s'.\n" "${schema}" "${table}"
         exit 255
     fi
 
diff --git a/src/share/database/scripts/mysql/upgrade_009.6_to_010.0.sh.in b/src/share/database/scripts/mysql/upgrade_009.6_to_010.0.sh.in
--- a/src/share/database/scripts/mysql/upgrade_009.6_to_010.0.sh.in
+++ b/src/share/database/scripts/mysql/upgrade_009.6_to_010.0.sh.in
@@ -58,8 +58,7 @@ for arg in "${@}"; do
 done
 
 # Make sure we have the schema.
-if [ -z "$schema" ]
-then
+if [ -z "${schema-}" ]; then
     printf "Could not find database schema name in cmd line args: %s\n" "${*}"
     exit 255
 fi
@@ -76,6 +75,11 @@ shrink_tag_column() {
         exit 255
     fi
 
+    if [ -z "${taglen-}" ]; then
+        printf "Could not determine tag length in schema '%s', table '%s'.\n" "${schema}" "${table}"
+        exit 255
+    fi
+
     # We aim for the length of 64 characters.
     if [ "$taglen" -ne 64 ]
     then
@@ -86,6 +90,12 @@ shrink_tag_column() {
             printf 'shrink_tag_column: select query failed [%s]\n' "${sql}"
             exit 255
         fi
+
+        if [ -z "${longtag-}" ]; then
+            printf "Could not determine how many tags exceed length of 64 in existing rows in schema '%s', table '%s'.\n" "${schema}" "${table}"
+            exit 255
+        fi
+
         # Report an error if there are any server tags exceeding 64 characters.
         # A user should fix the tags and rerun this migration.
         if [ "$longtag" -eq 1 ]
