[#90] The wipe_data.sh script is a bit more robust now

diff --git a/src/share/database/scripts/mysql/wipe_data.sh.in b/src/share/database/scripts/mysql/wipe_data.sh.in
--- a/src/share/database/scripts/mysql/wipe_data.sh.in
+++ b/src/share/database/scripts/mysql/wipe_data.sh.in
@@ -32,6 +32,11 @@ else
 fi
 
 # First argument is must be the expected schema version <major>.<minor>
+# Check if it's passed at all.
+if [ "$#" -lt "1" ]; then
+    printf "Required at least one parameter: schema version number, e.g. 7.0\n"
+    exit 1
+fi
 exp_version="$1"
 shift
 
