[#526,!269] Addressed more review comments
src/lib/cql/testutils/cql_schema.*
    Modified to use common softWipeEnabled(), which
    defaults to true

src/lib/database/testutils/schema.*
    bool softWipeEnabled() - new function that checks
    env varible to determine if DB data wiping is enabled
    (default is true/enabled)

src/lib/mysql/testutils/mysql_schema.*
    createMySQLSchema()
    destroyMySQLSchema()-  now softWipeEnabled() to allow
    data wiping to be turned on/off

src/share/database/scripts/mysql/wipe_data.sh.in
    Added better error messaging

several files:
    Removed extraneous calls to destroyMySQLSchema, added
    comments

diff --git a/src/share/database/scripts/mysql/wipe_data.sh.in b/src/share/database/scripts/mysql/wipe_data.sh.in
--- a/src/share/database/scripts/mysql/wipe_data.sh.in
+++ b/src/share/database/scripts/mysql/wipe_data.sh.in
@@ -28,8 +28,13 @@ shift;
 
 # If the existing schema doesn't match, the fail
 VERSION=`mysql_version "$@"`
+if [ "$VERSION" = "" ]; then
+    printf "Cannot wipe data, schema version could not be detected.\n"
+    exit 1
+fi
+
 if [ "$VERSION" != "$exp_version" ]; then
-    printf "Reported version is $VERSION is wrong, expected $exp_version.\n"
+    printf "Cannot wipe data, wrong schema version. Expected $exp_version, found version $VERSION.\n"
     exit 1
 fi
 
