[#3731] Fix doc installation in Meson

diff --git a/doc/sphinx/make-doc.sh.in b/doc/sphinx/make-doc.sh.in
--- a/doc/sphinx/make-doc.sh.in
+++ b/doc/sphinx/make-doc.sh.in
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-set -euv
+set -eu
+
+if test '@SPHINXBUILD@' = 'false'; then
+    echo 'Warning: sphinx-build is missing. Not creating docs.' >&2
+    exit 0
+fi
 
 cd '@builddir@'
 
@@ -9,20 +14,6 @@ cd '@builddir@'
 
 rm -f '@srcdir@/arm/platforms.rst'
 cp '@TOP_SOURCE_DIR@/platforms.rst' '@srcdir@/arm/platforms.rst'
-
-# pdf
-if test '@HAVE_PDFLATEX@' != 'no'; then
-    @SPHINXBUILD@ -M latex @srcdir@ @sphinxbuilddir@ @sphinxopts@
-    cd '@abs_sphinxbuilddir@/latex'
-    @PDFLATEX_AND_OPTS@ kea-arm.tex
-    makeindex -s python.ist kea-arm.idx
-    @PDFLATEX_AND_OPTS@ kea-arm.tex
-    @PDFLATEX_AND_OPTS@ kea-messages.tex
-    makeindex -s python.ist kea-messages.idx
-    @PDFLATEX_AND_OPTS@ kea-messages.tex
-fi
-
-cd '@builddir@'
 
 # html
 @SPHINXBUILD@ -M html @srcdir@ @sphinxbuilddir@ @sphinxopts@
@@ -35,3 +26,15 @@ cd '@builddir@'
 
 # mans
 @SPHINXBUILD@ -M man @srcdir@ @sphinxbuilddir@ @sphinxopts@
+
+# pdf
+if test '@HAVE_PDFLATEX@' != 'no'; then
+    @SPHINXBUILD@ -M latex @srcdir@ @sphinxbuilddir@ @sphinxopts@
+    cd '@abs_sphinxbuilddir@/latex'
+    @PDFLATEX_AND_OPTS@ kea-arm.tex
+    makeindex -s python.ist kea-arm.idx
+    @PDFLATEX_AND_OPTS@ kea-arm.tex
+    @PDFLATEX_AND_OPTS@ kea-messages.tex
+    makeindex -s python.ist kea-messages.idx
+    @PDFLATEX_AND_OPTS@ kea-messages.tex
+fi
