[963] improve exit status
0 on success (or upgrade aborted by user)
1 on check and need update
2 on check and version of db too high
3 on command-line error
4 on db read error
5 on upgrade error

diff --git a/src/bin/dbutil/tests/dbutil_test.sh.in b/src/bin/dbutil/tests/dbutil_test.sh.in
--- a/src/bin/dbutil/tests/dbutil_test.sh.in
+++ b/src/bin/dbutil/tests/dbutil_test.sh.in
@@ -269,9 +269,9 @@ record_count_test() {
 check_version() {
     copy_file $1 $verfile
     ../run_dbutil.sh --check $verfile
-    if [ $? -ne 0 ]
+    if [ $? -gt 2 ]
     then
-        fail "version check failed on database $1"
+        fail "version check failed on database $1; return code $?"
     else
         ../run_dbutil.sh --check $verfile | grep "$2" > /dev/null
         if [ $? -ne 0 ]
