implemented getPage4 and getPage6 for Cassandra, sorting and filtering hosts in unittests, implemented migration script for schema 4.0

diff --git a/src/bin/admin/tests/cql_tests.sh.in b/src/bin/admin/tests/cql_tests.sh.in
--- a/src/bin/admin/tests/cql_tests.sh.in
+++ b/src/bin/admin/tests/cql_tests.sh.in
@@ -85,7 +85,7 @@ cql_lease_version_test() {
 
     # Verify that kea-admin lease-version returns the correct version.
     version=$($keaadmin lease-version cql -u $db_user -p $db_password -n $db_name)
-    assert_str_eq "3.0" $version "Expected kea-admin to return %s, returned value was %s"
+    assert_str_eq "4.0" $version "Expected kea-admin to return %s, returned value was %s"
 
     # Wipe the database.
     cql_wipe
@@ -150,17 +150,15 @@ cql_lease4_dump_test() {
     # 1433464245 corresponds to 2015-05-05 02:30:45
     # 1436173267 corresponds to 2015-06-06 11:01:07
     insert_cql="\
-INSERT INTO lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
- fqdn_fwd, fqdn_rev, hostname, state, user_context)\
- VALUES(-1073741302,textAsBlob('20'),textAsBlob('30'),40,1430694930,50,true,true,\
- 'one.example.com', 0, '');\
-INSERT INTO lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
- fqdn_fwd, fqdn_rev, hostname, state, user_context)\
- VALUES(-1073741301,NULL,textAsBlob('123'),40,1433464245,50,true,true,'', 1, '');\
-INSERT INTO lease4(address, hwaddr, client_id, valid_lifetime, expire, subnet_id,\
- fqdn_fwd, fqdn_rev, hostname, state, user_context)\
- VALUES(-1073741300,textAsBlob('22'),NULL,40,1436173267,50,true,true,\
- 'three.example.com', 2, '');"
+  INSERT INTO lease4 (address, hwaddr, client_id, valid_lifetime, expire, subnet_id, \
+    fqdn_fwd, fqdn_rev, hostname, state, user_context) \
+    VALUES (-1073741302,textAsBlob('20'),textAsBlob('30'),40,1430694930,50,true,true,'one.example.com', 0, '');\
+  INSERT INTO lease4 (address, hwaddr, client_id, valid_lifetime, expire, subnet_id, \
+    fqdn_fwd, fqdn_rev, hostname, state, user_context) \
+    VALUES (-1073741301,NULL,textAsBlob('123'),40,1433464245,50,true,true,'', 1, '');\
+  INSERT INTO lease4 (address, hwaddr, client_id, valid_lifetime, expire, subnet_id, \
+    fqdn_fwd, fqdn_rev, hostname, state, user_context) \
+    VALUES (-1073741300,textAsBlob('22'),NULL,40,1436173267,50,true,true,'three.example.com', 2, '');"
 
     cql_execute "$insert_cql"
     assert_eq 0 $? "insert into lease4 failed, expected exit code %d, actual %d"
@@ -217,21 +215,21 @@ cql_lease6_dump_test() {
     # 1433464245 corresponds to 2015-05-05 02:30:45
     # 1436173267 corresponds to 2015-06-06 11:01:07
     insert_cql="\
-INSERT INTO lease6(address, duid, valid_lifetime, expire, subnet_id,\
- pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
- hwaddr, hwtype, hwaddr_source, state, user_context)\
- VALUES('2001:db8::10',textAsBlob('20'),30,1430694930,40,50,1,60,70,true,true,\
- 'one.example.com',textAsBlob('80'),90,16,0,'');\
-INSERT INTO lease6(address, duid, valid_lifetime, expire, subnet_id,\
- pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
- hwaddr, hwtype, hwaddr_source, state, user_context)\
- VALUES('2001:db8::11',NULL,30,1433464245,40,50,1,60,70,true,true,\
- '',textAsBlob('80'),90,1,1,'');\
-INSERT INTO lease6(address, duid, valid_lifetime, expire, subnet_id,\
- pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname,\
- hwaddr, hwtype, hwaddr_source, state, user_context)\
- VALUES('2001:db8::12',textAsBlob('21'),30,1436173267,40,50,1,60,70,true,true,\
- 'three.example.com',textAsBlob('80'),90,4,2,'');"
+  INSERT INTO lease6 (address, duid, valid_lifetime, expire, subnet_id, \
+    pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname, \
+    hwaddr, hwtype, hwaddr_source, state, user_context) \
+    VALUES ('2001:db8::10',textAsBlob('20'),30,1430694930,40,50,1,60,70,true,true, \
+      'one.example.com',textAsBlob('80'),90,16,0,'');\
+  INSERT INTO lease6 (address, duid, valid_lifetime, expire, subnet_id, \
+    pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname, \
+    hwaddr, hwtype, hwaddr_source, state, user_context) \
+    VALUES ('2001:db8::11',NULL,30,1433464245,40,50,1,60,70,true,true, \
+      '',textAsBlob('80'),90,1,1,'');\
+  INSERT INTO lease6 (address, duid, valid_lifetime, expire, subnet_id, \
+    pref_lifetime, lease_type, iaid, prefix_len, fqdn_fwd, fqdn_rev, hostname, \
+    hwaddr, hwtype, hwaddr_source, state, user_context) \
+    VALUES ('2001:db8::12',textAsBlob('21'),30,1436173267,40,50,1,60,70,true,true, \
+      'three.example.com',textAsBlob('80'),90,4,2,'');"
 
     cql_execute "$insert_cql"
     assert_eq 0 $? "insert into lease6 failed, expected exit code %d, actual %d"
@@ -260,7 +258,7 @@ cql_upgrade_schema_to_version() {
 
     # Check if the scripts directory exists at all.
     if [ ! -d ${db_scripts_dir}/cql ]; then
-        log_error "Invalid scripts directory: ${db_scripts_dir}/mysql"
+        log_error "Invalid scripts directory: ${db_scripts_dir}/cql"
         exit 1
     fi
 
@@ -306,17 +304,17 @@ cql_unused_subnet_id_test() {
     cql_upgrade_schema_to_version 2.0
 
     # Now we need insert some hosts to "migrate" for both v4 and v6
-    qry=\
-"insert into host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
-   values (1, 0, textAsBlob('0123456'), 0, 0, 0);\
- insert into host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
-   values (2, 0, textAsBlob('1123456'), 4, 0, 4);\
- insert into host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
-   values (3, 0, textAsBlob('2123456'), 0, 6, 6);\
- insert into host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
-   values (4, 0, textAsBlob('3123456'), 4, 6, 0);\
- insert into host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id)\
-   values (5, 0, textAsBlob('3123456'), -1, 6, 6);"
+    qry="\
+  INSERT INTO host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id) \
+    VALUES (1, 0, textAsBlob('0123456'), 0, 0, 0);\
+  INSERT INTO host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id) \
+    VALUES (2, 0, textAsBlob('1123456'), 4, 0, 4);\
+  INSERT INTO host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id) \
+    VALUES (3, 0, textAsBlob('2123456'), 0, 6, 6);\
+  INSERT INTO host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id) \
+    VALUES (4, 0, textAsBlob('3123456'), 4, 6, 0);\
+  INSERT INTO host_reservations (id, host_identifier_type, host_identifier, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id) \
+    VALUES (5, 0, textAsBlob('3123456'), -1, 6, 6);"
 
     cql_execute "$qry"
     assert_eq 0 $? "insert hosts failed, expected exit code: %d, actual: %d"
@@ -337,18 +335,110 @@ cql_unused_subnet_id_test() {
     # Fetch host_reservation data for comparison
     echo "Exporting host_reservation data to $export_file ..."
 
-    qry=\
-"select id, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id from\
- host_reservations where id in(1,2,3,4,5);"
+    qry="\
+  SELECT id, host_ipv4_subnet_id, host_ipv6_subnet_id, option_subnet_id\
+    FROM hosts WHERE id IN (1,2,3,4,5) ALLOW FILTERING;"
 
-    cql_execute "$qry" >$export_file
+    cql_execute "$qry" > $export_file
     assert_eq 0 $? "insert hosts failed, expected exit code: %d, actual: %d"
     # Compare the dump output to reference file, they should be identical.
-    cmp -s $export_file  $ref_file
+    cmp -s $export_file $ref_file
     assert_eq 0 $? "export file does not match reference file, expected exit code %d, actual %d"
 
     # remove the output file.
     rm $export_file
+
+    # Wipe the database.
+    cql_wipe
+
+    # Report test success.
+    test_finish 0
+}
+
+# Verifies that you can upgrade from an earlier version and
+# that all hosts and options from old host_reseravation table (version 3.0) are
+# converted to new schema (version 4.0) with new key partition key and are
+# moved to new hosts table
+cql_upgrade_hosts_test() {
+    test_start "cql.update_hosts_test"
+
+    # Let's wipe the whole database
+    cql_wipe
+
+    # We need to create an older database with lease data so we can
+    # verify the upgrade mechanisms which convert subnet id values
+    #
+    # Initialize database to schema 1.0.
+    cql_execute_script @abs_top_srcdir@/src/bin/admin/tests/dhcpdb_create_1.0.cql
+
+    # Now upgrade to schema 3.0, the version just before global HRs
+    cql_upgrade_schema_to_version 3.0
+
+    # Now we need insert some hosts to "migrate" for both v4 and v6
+    test_dir="@abs_top_srcdir@/src/bin/admin/tests"
+    data_file="$test_dir/data/cql.hosts_data_test.csv"
+    ref_file="$test_dir/data/cql.hosts_data_test.reference.csv"
+
+    output_dir="@abs_top_builddir@/src/bin/admin/tests"
+    export_file="$output_dir/data/cql.hosts_test.csv"
+    sorted_file="$output_dir/data/cql.hosts_test.sorted.csv"
+
+    # Fetch host_reservation data for comparison
+    echo "Exporting host_reservation data to $export_file ..."
+
+    qry="\
+  COPY host_reservations \
+        (id, host_identifier, host_identifier_type, host_ipv4_subnet_id, \
+         host_ipv6_subnet_id, host_ipv4_address, host_ipv4_next_server, \
+         host_ipv4_server_hostname, host_ipv4_boot_file_name, hostname, \
+         auth_key, user_context, host_ipv4_client_classes, \
+         host_ipv6_client_classes, reserved_ipv6_prefix_address, \
+         reserved_ipv6_prefix_length, reserved_ipv6_prefix_address_type, \
+         iaid, option_universe, option_code, option_value, \
+         option_formatted_value, option_space, option_is_persistent, \
+         option_client_class, option_subnet_id, option_user_context, \
+         option_scope_id) \
+    FROM '$data_file'"
+
+    cql_execute "$qry"
+    assert_eq 0 $? "insert hosts failed, expected exit code: %d, actual: %d"
+
+    # Ok, we have a 3.0 database with hosts and options. Let's upgrade it.
+    ${keaadmin} lease-upgrade cql -u $db_user -p $db_password -n $db_name -d $db_scripts_dir
+    ERRCODE=$?
+
+    # Upgrade should succeed
+    assert_eq 0 $ERRCODE "upgrade failed"
+
+    qry="\
+  COPY hosts \
+        (id, key, host_identifier, host_identifier_type, host_ipv4_subnet_id, \
+         host_ipv6_subnet_id, host_ipv4_address, host_ipv4_next_server, \
+         host_ipv4_server_hostname, host_ipv4_boot_file_name, hostname, \
+         auth_key, user_context, host_ipv4_client_classes, \
+         host_ipv6_client_classes, reserved_ipv6_prefix_address, \
+         reserved_ipv6_prefix_length, reserved_ipv6_prefix_address_type, \
+         iaid, option_universe, option_code, option_value, \
+         option_formatted_value, option_space, option_is_persistent, \
+         option_client_class, option_subnet_id, option_user_context, \
+         option_scope_id) \
+    TO '$export_file'"
+
+    cql_execute "$qry"
+    assert_eq 0 $? "insert hosts failed, expected exit code: %d, actual: %d"
+
+    # sort data so we can compare
+    cat $export_file | sort -V > $sorted_file
+
+    # Compare the dump output to reference file, they should be identical.
+    cmp -s $sorted_file $ref_file
+    assert_eq 0 $? "export file does not match reference file, expected exit code %d, actual %d"
+
+    # remove the output file.
+    rm $export_file
+
+    # remove the sorted file.
+    rm $sorted_file
 
     # Wipe the database.
     cql_wipe
@@ -365,3 +455,4 @@ cql_upgrade_test
 cql_lease4_dump_test
 cql_lease6_dump_test
 cql_unused_subnet_id_test
+cql_upgrade_hosts_test
