[3770] Added -t to kea-dhcp4 too

diff --git a/src/bin/dhcp4/tests/dhcp4_process_tests.sh.in b/src/bin/dhcp4/tests/dhcp4_process_tests.sh.in
--- a/src/bin/dhcp4/tests/dhcp4_process_tests.sh.in
+++ b/src/bin/dhcp4/tests/dhcp4_process_tests.sh.in
@@ -57,6 +57,41 @@ CONFIG="{
         ]
     }
 }"
+# Invalid configuration (syntax error) to check that Kea can check syntax.
+CONFIG_BAD_SYNTAX="{
+    \"Dhcp4\":
+    {
+        \"interfaces\": [ ],
+        \"valid-lifetime\": 4000,
+        \"renew-timer\": 1000,
+        \"rebind-timer\": 2000,
+        \"lease-database\":
+        {
+            \"type\": \"memfile\",
+            \"persist\": false
+        },
+        \"subnet4\": [
+        {
+            \"subnet\": \"10.0.0.0/8\",
+            \"pool\": [ { \"pool\": \"10.0.0.10-10.0.0.100\" } ]
+        } ]
+    },
+
+    \"Logging\":
+    {
+        \"loggers\": [
+        {
+            \"name\": \"kea-dhcp4\",
+            \"output_options\": [
+                {
+                    \"output\": \"$LOG_FILE\"
+                }
+            ],
+            \"severity\": \"INFO\"
+        }
+        ]
+    }
+}"
 # Invalid configuration (negative valid-lifetime) to check that Kea
 # gracefully handles reconfiguration errors.
 CONFIG_INVALID="{
@@ -102,6 +137,36 @@ bin_path=@abs_top_builddir@/src/bin/dhcp4
 
 # Import common test library.
 . @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+
+# This test verifies that syntax check works properly.
+syntax_check_test() {
+    # Log the start of the test and print test name.
+    test_start "dhcpv4_srv.syntax_check"
+    # Remove dangling Kea instances and remove log files.
+    cleanup
+    # Create correct configuration file.
+    create_config "${CONFIG}"
+    # Check it
+    printf "Running command %s.\n" "\"${bin_path}/${bin} -t -c ${CFG_FILE}\""
+    ${bin_path}/${bin} -t -c ${CFG_FILE}
+    exit_code=$?
+    if [ ${exit_code} -ne 0 ]; then
+        printf "ERROR: expected exit code 0, got ${exit_code}\n"
+        clean_exit 1
+    fi
+    # Create incorrect configuration file.
+    create_config "${CONFIG_BAD_SYNTAX}"
+    # Check it
+    printf "Running command %s.\n" "\"${bin_path}/${bin} -t -c ${CFG_FILE}\""
+    printf "A syntax error should be detected\n"
+    ${bin_path}/${bin} -t -c ${CFG_FILE}
+    if [ $? -eq 0 ]; then
+        printf "ERROR: expected exit code not 0, got 0\n"
+        clean_exit 1
+    fi
+    # All ok
+    clean_exit 0
+}
 
 # This test verifies that DHCPv4 can be reconfigured with a SIGHUP signal.
 dynamic_reconfiguration_test() {
@@ -380,3 +445,4 @@ shutdown_test "dhcpv4.sigint_test" 2
 version_test "dhcpv4.version"
 logger_vars_test "dhcpv4.variables"
 lfc_timer_test
+syntax_check_test
