[3929] config_report.cc is now generated during src/lib/cfgrpt/Makefile
By generating config_report.cc in the cfgrpt directory Makefile
rather than configure, it can be treated as any other generated
source file, rather than a one-off special case.

Moved cfgrpt directory from bin to lib since it creates a library
rather than an executable.

mk_cfgrpt.sh is now generated by configure from a .in file and

Details:

configure.ac
   removed call to mk_cfgrpts.sh
   added mk_cfgprt.sh to list of files generated by configure

src/bin/Makefile.am
   removed cfgrpt dir

changed cfgrpt directory to lib
    src/bin/d2/Makefile.am
    src/bin/d2/tests/Makefile.am
    src/bin/dhcp4/Makefile.am
    src/bin/dhcp4/tests/Makefile.am
    src/bin/dhcp6/Makefile.am
    src/bin/dhcp6/tests/Makefile.am
    src/bin/lfc/Makefile.am
    src/bin/lfc/tests/Makefile.am
    src/bin/perfdhcp/Makefile.am
    src/bin/perfdhcp/tests/Makefile.am

src/lib/Makefile.am
    added cfgrpt dir

src/lib/cfgrpt/Makefile.am
    changed include dir to be in lib not dir
    added config_report.cc to CLEANFILES
    added config_report.cc to BUILD_SOURCES
    removed config_report.cc from libcfgrpt_la_SOURCES
    added rule for config_report.cc to call mk_cfgrpt.sh

diff --git a/tools/mk_cfgrpt.sh.in b/tools/mk_cfgrpt.sh.in
--- a/tools/mk_cfgrpt.sh.in
+++ b/tools/mk_cfgrpt.sh.in
@@ -17,10 +17,22 @@
 # Called by configure
 #
 
-dest=$1
+dest="$1"
+report_file="@abs_top_builddir@/config.report"
+
+if [ -z ${report_file} ]
+then
+    echo "ERROR mk_cfgrpt.sh - input report: $report_file does not exist"
+    exit -1
+fi
 
 # Initializes
-cat > $dest
+cat /dev/null > $dest
+if [ $? -ne 0 ]
+then
+    echo "ERROR mk_cfgrpt.sh - cannot create config output file: $dest"
+    exit -1
+fi
 
 # Header
 cat >> $dest << END
@@ -34,7 +46,7 @@ END
 
 # Body: escape '\'s and '"'s, preprend '    ";;;; ' and append '",'
 sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    ";;;; /' -e 's/$/",/' \
-    < config.report >> $dest
+    < $report_file >> $dest
 
 # Trailer
 cat >> $dest <<END
