[#1574] make all shell scripts POSIX compliant
* solve all shellcheck warnings
* shebang in all scripts
* set -eu everywhere
* make scripts callable from everywhere
* quote variables to prevent globbing and word splitting
* add missing copyrights
* remove unused variables
* use $() instead of backticks ``
... and so on

diff --git a/src/bin/agent/tests/ca_process_tests.sh.in b/src/bin/agent/tests/ca_process_tests.sh.in
--- a/src/bin/agent/tests/ca_process_tests.sh.in
+++ b/src/bin/agent/tests/ca_process_tests.sh.in
@@ -1,15 +1,28 @@
+#!/bin/sh
+
 # Copyright (C) 2016-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Include common test library.
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
+
 # Path to the temporary configuration file.
-CFG_FILE=@abs_top_builddir@/src/bin/agent/tests/test_config.json
+CFG_FILE="@abs_top_builddir@/src/bin/agent/tests/test_config.json"
 # Path to the Control Agent log file.
-LOG_FILE=@abs_top_builddir@/src/bin/agent/tests/test.log
-# Expected version
-EXPECTED_VERSION="@PACKAGE_VERSION@"
+LOG_FILE="@abs_top_builddir@/src/bin/agent/tests/test.log"
 
 # Control Agent configuration to be stored in the configuration file.
 # todo: use actual configuration once we support it.
@@ -66,33 +79,33 @@ CONFIG_PWD="{
 }"
 
 bin="kea-ctrl-agent"
-bin_path=@abs_top_builddir@/src/bin/agent
+bin_path="@abs_top_builddir@/src/bin/agent"
 
 # Import common test library.
-. @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # This test verifies that syntax checking works properly. This function
 # requires 3 parameters:
-# testname
+# test_name
 # config - string with a content of the config (will be written to a file)
-# exp_code - expected exit code returned by kea (0 - success, 1 - failure)
+# expected_code - expected exit code returned by kea (0 - success, 1 - failure)
 syntax_check_test() {
-    local TESTNAME="${1}"
-    local CONFIG="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local config="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create correct configuration file.
-    create_config "${CONFIG}"
+    create_config "${config}"
     # Check it
-    printf "Running command %s.\n" "\"${bin_path}/${bin} -t ${CFG_FILE}\""
-    ${bin_path}/${bin} -t ${CFG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    printf 'Running command %s.\n' "\"${bin_path}/${bin} -t ${CFG_FILE}\""
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" -t "${CFG_FILE}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
     test_finish 0
@@ -104,7 +117,7 @@ shutdown_test() {
     test_name=${1}  # Test name
     signum=${2}      # Signal number
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
     # Remove dangling D2 instances and remove log files.
     cleanup
     # Create new configuration file.
@@ -115,7 +128,7 @@ shutdown_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for Control Agent to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Control Agent to start.\n"
         clean_exit 1
     fi
@@ -123,35 +136,35 @@ shutdown_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Control Agent process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured.
     # It should be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
-        printf "ERROR: server been configured ${_GET_RECONFIGS} time(s), but exactly 1 was expected.\n"
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
+        printf 'ERROR: server been configured %s time(s), but exactly 1 was expected.\n' "${_GET_RECONFIGS}"
         clean_exit 1
     else
         printf "Server successfully configured.\n"
     fi
 
     # Send signal to Control Agent (SIGTERM, SIGINT etc.)
-    send_signal ${signum} ${bin}
+    send_signal "${signum}" "${bin}"
 
     # Now wait for process to log that it is exiting.
     wait_for_message 10 "DCTL_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Control Agent did not log shutdown.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     test_finish 0
@@ -159,39 +172,35 @@ shutdown_test() {
 
 # This test verifies that passwords are redacted in logs.
 # This function takes 2 parameters:
-# testname
+# test_name
 # config - string with a content of the config (will be written to a file)
-# exp_code - expected exit code returned by kea (0 - success, 1 - failure)
+# expected_code - expected exit code returned by kea (0 - success, 1 - failure)
 password_redact_test() {
-    local TESTNAME="${1}"
-    local CONFIG="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local config="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create correct configuration file.
-    create_config "${CONFIG}"
+    create_config "${config}"
     # Instruct Control Agent to log to the specific file.
     set_logger
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin} -d -t ${CFG_FILE}\""
-    ${bin_path}/${bin} -d -t ${CFG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" -d -t "${CFG_FILE}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
-    grep "sensitive" ${LOG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne 1 ]; then
+    if grep -q 'sensitive' "${LOG_FILE}"; then
         printf "ERROR: sensitive is present in logs\n"
         clean_exit 1
     fi
-    grep -q "superadmin" ${LOG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne 0 ]; then
+    if ! grep -q 'superadmin' "${LOG_FILE}"; then
         printf "ERROR: superadmin is not present in logs\n"
         clean_exit 1
     fi
diff --git a/src/bin/d2/tests/d2_process_tests.sh.in b/src/bin/d2/tests/d2_process_tests.sh.in
--- a/src/bin/d2/tests/d2_process_tests.sh.in
+++ b/src/bin/d2/tests/d2_process_tests.sh.in
@@ -1,15 +1,25 @@
+#!/bin/sh
+
 # Copyright (C) 2014-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 # Path to the temporary configuration file.
-CFG_FILE=@abs_top_builddir@/src/bin/d2/tests/test_config.json
+CFG_FILE="@abs_top_builddir@/src/bin/d2/tests/test_config.json"
 # Path to the D2 log file.
-LOG_FILE=@abs_top_builddir@/src/bin/d2/tests/test.log
-# Expected version
-EXPECTED_VERSION="@PACKAGE_VERSION@"
+LOG_FILE="@abs_top_builddir@/src/bin/d2/tests/test.log"
 # D2 configuration to be stored in the configuration file.
 CONFIG="{
     \"DhcpDdns\":
@@ -105,33 +115,33 @@ CONFIG_INVALID="{
 
 # Set the location of the executable.
 bin="kea-dhcp-ddns"
-bin_path=@abs_top_builddir@/src/bin/d2
+bin_path="@abs_top_builddir@/src/bin/d2"
 
 # Import common test library.
-. @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # This test verifies that syntax checking works properly. This function
 # requires 3 parameters:
-# testname
+# test_name
 # config - string with a content of the config (will be written to a file)
-# exp_code - expected exit code returned by kea (0 - success, 1 - failure)
+# expected_code - expected exit code returned by kea (0 - success, 1 - failure)
 syntax_check_test() {
-    local TESTNAME="${1}"
-    local CONFIG="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local config="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create correct configuration file.
-    create_config "${CONFIG}"
+    create_config "${config}"
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin} -t ${CFG_FILE}\""
-    ${bin_path}/${bin} -t ${CFG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" -t "${CFG_FILE}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
     test_finish 0
@@ -151,7 +161,7 @@ dynamic_reconfiguration_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for D2 to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for D2 to start.\n"
         clean_exit 1
     fi
@@ -159,16 +169,16 @@ dynamic_reconfiguration_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one D2 process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured.
     # It should be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
         printf "ERROR: D2 hasn't been configured.\n"
         clean_exit 1
     else
@@ -183,7 +193,7 @@ dynamic_reconfiguration_test() {
 
     # Wait up to 10s for the D2Controller to log reload signal received.
     wait_for_message 10 "DCTL_CFG_FILE_RELOAD_SIGNAL_RECVD"  1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: D2 did report the reload signal receipt.\n"
         clean_exit 1
     fi
@@ -192,14 +202,14 @@ dynamic_reconfiguration_test() {
     # The configuration provided is invalid so it should result in
     # reconfiguration failure but the server should still be running.
     wait_for_message 10 "DCTL_CFG_FILE_RELOAD_ERROR" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: D2 did not report reload error.\n"
         clean_exit 1
     fi
 
     # Make sure the server is still operational.
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: D2 was killed when attempting reconfiguration.\n"
         clean_exit 1
     fi
@@ -217,7 +227,7 @@ dynamic_reconfiguration_test() {
     # After receiving SIGHUP the server should get reconfigured and the
     # reconfiguration should be noted in the log file. We should now
     # have two configurations logged in the log file.
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: D2 hasn't been reconfigured.\n"
         clean_exit 1
     else
@@ -226,7 +236,7 @@ dynamic_reconfiguration_test() {
 
     # Make sure the server is still operational.
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: D2 was killed when attempting reconfiguration.\n"
         clean_exit 1
     fi
@@ -238,10 +248,10 @@ dynamic_reconfiguration_test() {
 # This test verifies that DHCPv4 server is shut down gracefully when it
 # receives a SIGINT or SIGTERM signal.
 shutdown_test() {
-    test_name=${1}  # Test name
-    signum=${2}      # Signal number
+    local test_name=${1}    # Test name
+    local signum=${2}       # Signal number
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
     # Remove dangling D2 instances and remove log files.
     cleanup
     # Create new configuration file.
@@ -252,7 +262,7 @@ shutdown_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for D2 to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for D2 to start.\n"
         clean_exit 1
     fi
@@ -260,16 +270,16 @@ shutdown_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one D2 process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured.
     # It should be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
         printf "ERROR: server hasn't been configured.\n"
         clean_exit 1
     else
@@ -277,18 +287,18 @@ shutdown_test() {
     fi
 
     # Send signal to D2 (SIGTERM, SIGINT etc.)
-    send_signal ${signum} ${bin}
+    send_signal "${signum}" "${bin}"
 
     # Now wait for process to log that it is exiting.
     wait_for_message 10 "DCTL_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: DHCP-DDNS did not log shutdown.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     test_finish 0
diff --git a/src/bin/dhcp6/tests/dhcp6_process_tests.sh.in b/src/bin/dhcp6/tests/dhcp6_process_tests.sh.in
--- a/src/bin/dhcp6/tests/dhcp6_process_tests.sh.in
+++ b/src/bin/dhcp6/tests/dhcp6_process_tests.sh.in
@@ -1,17 +1,27 @@
+#!/bin/sh
+
 # Copyright (C) 2014-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 # Path to the temporary configuration file.
-CFG_FILE=@abs_top_builddir@/src/bin/dhcp6/tests/test_config.json
+CFG_FILE="@abs_top_builddir@/src/bin/dhcp6/tests/test_config.json"
 # Path to the Kea log file.
-LOG_FILE=@abs_top_builddir@/src/bin/dhcp6/tests/test.log
+LOG_FILE="@abs_top_builddir@/src/bin/dhcp6/tests/test.log"
 # Path to the Kea lease file.
-LEASE_FILE=@abs_top_builddir@/src/bin/dhcp6/tests/test_leases.csv
-# Expected version
-EXPECTED_VERSION="@PACKAGE_VERSION@"
+LEASE_FILE="@abs_top_builddir@/src/bin/dhcp6/tests/test_leases.csv"
 # Kea configuration to be stored in the configuration file.
 CONFIG="{
     \"Dhcp6\":
@@ -163,33 +173,33 @@ CONFIG_BAD_VALUES="{
 
 # Set the location of the executable.
 bin="kea-dhcp6"
-bin_path=@abs_top_builddir@/src/bin/dhcp6
+bin_path="@abs_top_builddir@/src/bin/dhcp6"
 
 # Import common test library.
-. @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # This test verifies that syntax checking works properly. This function
 # requires 3 parameters:
-# testname
+# test_name
 # config - string with a content of the config (will be written to a file)
-# exp_code - expected exit code returned by kea (0 - success, 1 - failure)
+# expected_code - expected exit code returned by kea (0 - success, 1 - failure)
 syntax_check_test() {
-    local TESTNAME="${1}"
-    local CONFIG="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local config="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create correct configuration file.
-    create_config "${CONFIG}"
+    create_config "${config}"
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin} -t ${CFG_FILE}\""
-    ${bin_path}/${bin} -t ${CFG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code $EXP_CODE, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" -t "${CFG_FILE}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
 
@@ -210,7 +220,7 @@ dynamic_reconfiguration_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for Kea to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Kea to start.\n"
         clean_exit 1
     fi
@@ -218,16 +228,16 @@ dynamic_reconfiguration_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Kea process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured. It should
     # be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
         printf "ERROR: server hasn't been configured.\n"
         clean_exit 1
     else
@@ -247,10 +257,10 @@ dynamic_reconfiguration_test() {
     # The configuration provided is invalid so it should result in
     # reconfiguration failure but the server should still be running.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
         printf "ERROR: server has been reconfigured despite bogus configuration.\n"
         clean_exit 1
-    elif [ ${_GET_RECONFIG_ERRORS} -ne 1 ]; then
+    elif [ "${_GET_RECONFIG_ERRORS}" -ne 1 ]; then
         printf "ERROR: server did not report reconfiguration error despite attempt\
  to configure it with invalid configuration.\n"
         clean_exit 1
@@ -258,7 +268,7 @@ dynamic_reconfiguration_test() {
 
     # Make sure the server is still operational.
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: Kea process was killed when attempting reconfiguration.\n"
         clean_exit 1
     fi
@@ -276,7 +286,7 @@ dynamic_reconfiguration_test() {
     # After receiving SIGHUP the server should get reconfigured and the
     # reconfiguration should be noted in the log file. We should now
     # have two configurations logged in the log file.
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: server hasn't been reconfigured.\n"
         clean_exit 1
     else
@@ -285,7 +295,7 @@ dynamic_reconfiguration_test() {
 
     # Make sure the server is still operational.
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: Kea process was killed when attempting reconfiguration.\n"
         clean_exit 1
     fi
@@ -293,7 +303,7 @@ dynamic_reconfiguration_test() {
     # When the server receives a signal the call to select() function is
     # interrupted. This should not be logged as an error.
     get_log_messages "DHCP6_PACKET_RECEIVE_FAIL"
-    assert_eq 0 ${_GET_LOG_MESSAGES} \
+    assert_eq 0 "${_GET_LOG_MESSAGES}" \
         "Expected get_log_messages DHCP6_PACKET_RECEIVE_FAIL return %d, \
 returned %d."
 
@@ -304,11 +314,11 @@ returned %d."
 # This test verifies that DHCPv6 server is shut down gracefully when it
 # receives a SIGINT or SIGTERM signal.
 shutdown_test() {
-    test_name=${1}  # Test name
-    signum=${2}      # Signal number
+    local test_name=${1}    # Test name
+    local signum=${2}       # Signal number
 
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create new configuration file.
@@ -319,7 +329,7 @@ shutdown_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for Kea to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Kea to start.\n"
         clean_exit 1
     fi
@@ -327,16 +337,16 @@ shutdown_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Kea process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured. It should
     # be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
         printf "ERROR: server hasn't been configured.\n"
         clean_exit 1
     else
@@ -344,25 +354,25 @@ shutdown_test() {
     fi
 
     # Send signal to Kea (SIGTERM, SIGINT etc.)
-    send_signal ${signum} ${bin}
+    send_signal "${signum}" "${bin}"
 
     # Wait up to 10s for the server's graceful shutdown. The graceful shut down
     # should be recorded in the log file with the appropriate message.
     wait_for_message 10 "DHCP6_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Server did not record shutdown in the log.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     # When the server receives a signal the call to select() function is
     # interrupted. This should not be logged as an error.
     get_log_messages "DHCP6_PACKET_RECEIVE_FAIL"
-    assert_eq 0 ${_GET_LOG_MESSAGES} \
+    assert_eq 0 "${_GET_LOG_MESSAGES}" \
         "Expected get_log_messages DHCP6_PACKET_RECEIVE_FAIL return %d, \
 returned %d."
 
@@ -378,7 +388,7 @@ lfc_timer_test() {
     cleanup
     # Create a configuration with the LFC enabled, by replacing the section
     # with the lfc-interval and persist parameters.
-    LFC_CONFIG=$(printf "${CONFIG}" | sed -e 's/\"lfc-interval\": 0/\"lfc-interval\": 3/g' \
+    LFC_CONFIG=$(printf '%s' "${CONFIG}" | sed -e 's/\"lfc-interval\": 0/\"lfc-interval\": 3/g' \
                         | sed -e 's/\"persist\": false,/\"persist\": true,/g')
     # Create new configuration file.
     create_config "${LFC_CONFIG}"
@@ -388,7 +398,7 @@ lfc_timer_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for Kea to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Kea to start.\n"
         clean_exit 1
     fi
@@ -396,15 +406,15 @@ lfc_timer_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Kea process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check if Kea emits the log message indicating that LFC is started.
     wait_for_message 10 "DHCPSRV_MEMFILE_LFC_EXECUTE" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Server did not execute LFC.\n"
         clean_exit 1
     fi
@@ -413,7 +423,7 @@ lfc_timer_test() {
     sleep 1
 
     # Modify the interval.
-    LFC_CONFIG=$(printf "${LFC_CONFIG}" | sed -e 's/\"lfc-interval\": 3/\"lfc-interval\": 4/g')
+    LFC_CONFIG=$(printf '%s' "${LFC_CONFIG}" | sed -e 's/\"lfc-interval\": 3/\"lfc-interval\": 4/g')
     # Create new configuration file.
     create_config "${LFC_CONFIG}"
 
@@ -427,7 +437,7 @@ lfc_timer_test() {
     # After receiving SIGHUP the server should get reconfigured and the
     # reconfiguration should be noted in the log file. We should now
     # have two configurations logged in the log file.
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: server hasn't been reconfigured.\n"
         clean_exit 1
     else
@@ -436,14 +446,14 @@ lfc_timer_test() {
 
     # Make sure the server is still operational.
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: Kea process was killed when attempting reconfiguration.\n"
         clean_exit 1
     fi
 
     # Wait for the LFC to run the second time.
     wait_for_message 10 "DHCPSRV_MEMFILE_LFC_EXECUTE" 2
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Server did not execute LFC.\n"
         clean_exit 1
     fi
@@ -454,14 +464,14 @@ lfc_timer_test() {
     # Wait up to 10s for the server's graceful shutdown. The graceful shut down
     # should be recorded in the log file with the appropriate message.
     wait_for_message 10 "DHCP6_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Server did not record shutdown in the log.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     # All ok. Shut down Kea and exit.
diff --git a/src/bin/netconf/tests/shtests/netconf_tests.sh.in b/src/bin/netconf/tests/shtests/netconf_tests.sh.in
--- a/src/bin/netconf/tests/shtests/netconf_tests.sh.in
+++ b/src/bin/netconf/tests/shtests/netconf_tests.sh.in
@@ -1,15 +1,25 @@
+#!/bin/sh
+
 # Copyright (C) 2018-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 # Path to the temporary configuration file.
-CFG_FILE=@abs_top_builddir@/src/bin/netconf/tests/shtests/test_config.json
+CFG_FILE="@abs_top_builddir@/src/bin/netconf/tests/shtests/test_config.json"
 # Path to the Kea log file.
-LOG_FILE=@abs_top_builddir@/src/bin/netconf/tests/shtests/test.log
-# Expected version
-EXPECTED_VERSION="@PACKAGE_VERSION@"
+LOG_FILE="@abs_top_builddir@/src/bin/netconf/tests/shtests/test.log"
 
 # Kea-netconf configuration to be stored in the configuration file.
 CONFIG="{
@@ -64,19 +74,19 @@ CONFIG_BAD_VALUE="{
 
 # Set the location of the executable.
 bin="kea-netconf"
-bin_path=@abs_top_builddir@/src/bin/netconf
+bin_path="@abs_top_builddir@/src/bin/netconf"
 
 # Import common test library.
-. @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # This test verifies that help can be printed out.
 usage_test() {
-    local TESTNAME="${1}"
-    local PARAMS="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local parameter="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
 
@@ -85,10 +95,10 @@ usage_test() {
 
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin} -t ${CFG_FILE}\""
-    ${bin_path}/${bin} ${PARAMS}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" "${parameter}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
     test_finish 0
@@ -96,20 +106,20 @@ usage_test() {
 
 # This test verifies that no argument is not reported as a PID file error.
 no_argument_test() {
-    local TESTNAME="${1}"
-    local EXP_CODE="${2}"
+    local test_name="${1}"
+    local expected_code="${2}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
 
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin}\""
-    ${bin_path}/${bin} | grep PID 2>&1
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
     test_finish 0
@@ -117,26 +127,26 @@ no_argument_test() {
 
 # This test verifies that syntax checking works properly. This function
 # requires 3 parameters:
-# testname
+# test_name
 # config - string with a content of the config (will be written to a file)
-# exp_code - expected exit code returned by kea (0 - success, 1 - failure)
+# expected_code - expected exit code returned by kea (0 - success, 1 - failure)
 syntax_check_test() {
-    local TESTNAME="${1}"
-    local CONFIG="${2}"
-    local EXP_CODE="${3}"
+    local test_name="${1}"
+    local config="${2}"
+    local expected_code="${3}"
 
     # Log the start of the test and print test name.
-    test_start $TESTNAME
+    test_start "${test_name}"
     # Remove dangling Kea instances and remove log files.
     cleanup
     # Create correct configuration file.
-    create_config "${CONFIG}"
+    create_config "${config}"
     # Check it
     printf "Running command %s.\n" "\"${bin_path}/${bin} -t ${CFG_FILE}\""
-    ${bin_path}/${bin} -t ${CFG_FILE}
-    exit_code=$?
-    if [ ${exit_code} -ne $EXP_CODE ]; then
-        printf "ERROR: expected exit code ${EXP_CODE}, got ${exit_code}\n"
+    run_and_return_output_and_exit_code \
+        "${bin_path}/${bin}" -t "${CFG_FILE}"
+    if [ "${EXIT_CODE}" -ne "${expected_code}" ]; then
+        printf 'ERROR: expected exit code %s, got %s\n' "${expected_code}" "${EXIT_CODE}"
         clean_exit 1
     fi
     test_finish 0
@@ -148,7 +158,7 @@ shutdown_test() {
     test_name=${1}  # Test name
     signum=${2}      # Signal number
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
     # Remove dangling Netconf instances and remove log files.
     cleanup
     # Create new configuration file.
@@ -159,7 +169,7 @@ shutdown_test() {
     start_kea ${bin_path}/${bin}
     # Wait up to 20s for Netconf Agent to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Netconf Agent to start.\n"
         clean_exit 1
     fi
@@ -167,35 +177,35 @@ shutdown_test() {
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
     get_pid ${bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Netconf Agent process to be started. Found %d processes\
- started.\n" ${_GET_PIDS_NUM}
+ started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured.
     # It should be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
-        printf "ERROR: server been configured ${_GET_RECONFIGS} time(s), but exactly 1 was expected.\n"
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
+        printf "ERROR: server been configured %s time(s), but exactly 1 was expected.\n" "${_GET_RECONFIGS}"
         clean_exit 1
     else
         printf "Server successfully configured.\n"
     fi
 
     # Send signal to Netconf Agent (SIGTERM, SIGINT etc.)
-    send_signal ${signum} ${bin}
+    send_signal "${signum}" "${bin}"
 
     # Now wait for process to log that it is exiting.
     wait_for_message 10 "DCTL_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Netconf Agent did not log shutdown.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     test_finish 0
diff --git a/src/bin/shell/tests/shell_process_tests.sh.in b/src/bin/shell/tests/shell_process_tests.sh.in
--- a/src/bin/shell/tests/shell_process_tests.sh.in
+++ b/src/bin/shell/tests/shell_process_tests.sh.in
@@ -1,13 +1,20 @@
+#!/bin/sh
+
 # Copyright (C) 2017-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-# Path to the temporary configuration file.
-CFG_FILE=@abs_top_builddir@/src/bin/shell/tests/test_config.json
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 # Path to the Control Agent log file.
-LOG_FILE=@abs_top_builddir@/src/bin/shell/tests/test.log
+LOG_FILE="@abs_top_builddir@/src/bin/shell/tests/test.log"
 # Expected version
 EXPECTED_VERSION="@PACKAGE_VERSION@"
 
@@ -36,15 +43,15 @@ CONFIG="{
 # Using bin and bin_path would be confusing, so we omit defining bin
 # and bin_path on purpose.
 ca_bin="kea-ctrl-agent"
-ca_bin_path=@abs_top_builddir@/src/bin/agent
+ca_bin_path="@abs_top_builddir@/src/bin/agent"
 
 shell_bin="kea-shell"
-shell_bin_path=@abs_top_builddir@/src/bin/shell
+shell_bin_path="@abs_top_builddir@/src/bin/shell"
 
-tmpfile_path=@abs_top_builddir@/src/bin/shell/tests
+tmpfile_path="@abs_top_builddir@/src/bin/shell/tests"
 
 # Import common test library.
-. @abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh
+. "@abs_top_builddir@/src/lib/testutils/dhcp_test_lib.sh"
 
 # This test verifies that Control Agent is shut down gracefully when it
 # receives a SIGINT or SIGTERM signal.
@@ -57,7 +64,7 @@ shell_command_test() {
     # Setup phase: start CA.
 
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
 
     # Remove any dangling CA instances and remove log files.
     cleanup
@@ -71,26 +78,26 @@ shell_command_test() {
     start_kea ${ca_bin_path}/${ca_bin}
     # Wait up to 20s for Control Agent to start.
     wait_for_kea 20
-    if [ ${_WAIT_FOR_KEA} -eq 0 ]; then
+    if [ "${_WAIT_FOR_KEA}" -eq 0 ]; then
         printf "ERROR: timeout waiting for Control Agent to start.\n"
         clean_exit 1
     fi
 
     # Check if it is still running. It could have terminated (e.g. as a result
     # of configuration failure).
-    get_pid ${ca_bin}
-    if [ ${_GET_PIDS_NUM} -ne 1 ]; then
+    get_pid "${ca_bin}"
+    if [ "${_GET_PIDS_NUM}" -ne 1 ]; then
         printf "ERROR: expected one Control Agent process to be started.\
- Found %d processes started.\n" ${_GET_PIDS_NUM}
+ Found %d processes started.\n" "${_GET_PIDS_NUM}"
         clean_exit 1
     fi
 
     # Check in the log file, how many times server has been configured.
     # It should be just once on startup.
     get_reconfigs
-    if [ ${_GET_RECONFIGS} -ne 1 ]; then
-        printf "ERROR: server been configured ${_GET_RECONFIGS} time(s),\
- but exactly 1 was expected.\n"
+    if [ "${_GET_RECONFIGS}" -ne 1 ]; then
+        printf "ERROR: server been configured %s time(s),\
+ but exactly 1 was expected.\n" "${_GET_RECONFIGS}"
         clean_exit 1
     else
         printf "Server successfully configured.\n"
@@ -102,11 +109,11 @@ shell_command_test() {
     echo "Executing kea-shell ($tmp)"
 
     echo "${params}" | ${shell_bin_path}/${shell_bin} --host 127.0.0.1 \
- --port 8081 ${cmd} > ${tmpfile_path}/shell-stdout.txt
+ --port 8081 "${cmd}" > ${tmpfile_path}/shell-stdout.txt
+    shell_exit_code=$?
 
     # Check the exit code
-    shell_exit_code=$?
-    if [ ${shell_exit_code} -ne 0 ]; then
+    if [ "${shell_exit_code}" -ne 0 ]; then
         echo "ERROR:" \
         "kea-shell returned ${shell_exit_code} exit code,  expected 0."
     else
@@ -115,10 +122,10 @@ shell_command_test() {
 
     # Now check the response
     rm -f ${tmpfile_path}/shell-expected.txt
-    echo ${exp_rsp} > ${tmpfile_path}/shell-expected.txt
+    printf '%s\n' "${exp_rsp}" > ${tmpfile_path}/shell-expected.txt
     diff ${tmpfile_path}/shell-stdout.txt ${tmpfile_path}/shell-expected.txt
     diff_code=$?
-    if [ ${diff_code} -ne 0 ]; then
+    if [ "${diff_code}" -ne 0 ]; then
         echo "ERROR:" \
         "content returned is different than expected." \
         "See ${tmpfile_path}/shell-*.txt"
@@ -139,14 +146,14 @@ shell_command_test() {
 
     # Now wait for process to log that it is exiting.
     wait_for_message 10 "DCTL_SHUTDOWN" 1
-    if [ ${_WAIT_FOR_MESSAGE} -eq 0 ]; then
+    if [ "${_WAIT_FOR_MESSAGE}" -eq 0 ]; then
         printf "ERROR: Control Agent did not log shutdown.\n"
         clean_exit 1
     fi
 
     # Make sure the server is down.
     wait_for_server_down 5 ${ca_bin}
-    assert_eq 1 ${_WAIT_FOR_SERVER_DOWN} \
+    assert_eq 1 "${_WAIT_FOR_SERVER_DOWN}" \
         "Expected wait_for_server_down return %d, returned %d"
 
     test_finish 0
@@ -157,14 +164,14 @@ version_test() {
     test_name=${1}  # Test name
 
     # Log the start of the test and print test name.
-    test_start ${test_name}
+    test_start "${test_name}"
 
     # Remove dangling Kea instances and remove log files.
     cleanup
 
-    REPORTED_VERSION="`${shell_bin_path}/${shell_bin} -v`"
+    REPORTED_VERSION=$(${shell_bin_path}/${shell_bin} -v)
 
-    if test "${REPORTED_VERSION}" == "${EXPECTED_VERSION}"; then
+    if test "${REPORTED_VERSION}" = "${EXPECTED_VERSION}"; then
         test_finish 0
     else
         echo "ERROR:" \
diff --git a/src/lib/log/tests/buffer_logger_test.sh.in b/src/lib/log/tests/buffer_logger_test.sh.in
--- a/src/lib/log/tests/buffer_logger_test.sh.in
+++ b/src/lib/log/tests/buffer_logger_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2012-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -7,26 +8,32 @@
 
 # Checks that the initLogger() call uses for unit tests respects the setting of
 # the buffer value
-#
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
 
 testname="bufferLogger test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-tempfile=@abs_builddir@/buffer_logger_test_tempfile_$$
+tempfile="@abs_builddir@/buffer_logger_test_tempfile_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
-echo "1. Checking that buffer initialization works"
+printf '1. Checking that buffer initialization works\n'
 
-echo -n  "   - Buffer including process() call: "
+printf '   - Buffer including process() call: '
 cat > $tempfile << .
 INFO  [buffertest.log] LOG_BAD_SEVERITY unrecognized log severity: info
 INFO  [buffertest.log] LOG_BAD_SEVERITY unrecognized log severity: info
@@ -36,7 +43,7 @@ INFO  [buffertest.log] LOG_BAD_SEVERITY unrecognized log severity: info
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n  "   - Buffer excluding process() call: "
+printf '   - Buffer excluding process() call: '
 cat > $tempfile << .
 INFO [buffertest.log]: LOG_BAD_SEVERITY unrecognized log severity: info
 DEBUG [buffertest.log]: LOG_BAD_DESTINATION unrecognized log destination: debug-50
@@ -44,8 +51,6 @@ INFO [buffertest.log]: LOG_BAD_SEVERITY unrecognized log severity: info
 .
 ./buffer_logger_test -n 2>&1 | diff $tempfile -
 passfail $?
-
-
 
 # Tidy up.
 rm -f $tempfile
diff --git a/src/lib/log/tests/console_test.sh.in b/src/lib/log/tests/console_test.sh.in
--- a/src/lib/log/tests/console_test.sh.in
+++ b/src/lib/log/tests/console_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2011-2016 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -8,39 +9,43 @@
 # The logger supports the idea of a "console" logger than logs to either stdout
 # or stderr.  This test checks that both these options work.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 testname="Console output test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-tempfile=@abs_builddir@/console_test_tempfile_$$
+tempfile="@abs_builddir@/console_test_tempfile_$$"
 
 # Look at tempfile and check that the count equals the expected count
 passfail() {
-    count=`wc -l $tempfile | awk '{print $1}'`
-    if [ $count -eq $1 ]; then
-        echo " pass"
+    count=$(wc -l $tempfile | awk '{print $1}')
+    if [ "${count}" -eq "${1}" ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
-echo -n "1. Checking that console output to stdout goes to stdout:"
+printf '1. Checking that console output to stdout goes to stdout:'
 rm -f $tempfile
 ./logger_example -c stdout -s error 1> $tempfile 2> /dev/null
 passfail 4
 
-echo -n "2. Checking that console output to stdout does not go to stderr:"
+printf '2. Checking that console output to stdout does not go to stderr:'
 rm -f $tempfile
 ./logger_example -c stdout -s error 1> /dev/null 2> $tempfile
 passfail 0
 
-echo -n "3. Checking that console output to stderr goes to stderr:"
+printf '3. Checking that console output to stderr goes to stderr:'
 rm -f $tempfile
 ./logger_example -c stderr -s error 1> /dev/null 2> $tempfile
 passfail 4
 
-echo -n "4. Checking that console output to stderr does not go to stdout:"
+printf '4. Checking that console output to stderr does not go to stdout:'
 rm -f $tempfile
 ./logger_example -c stderr -s error 1> $tempfile 2> /dev/null
 passfail 0
diff --git a/src/lib/log/tests/destination_test.sh.in b/src/lib/log/tests/destination_test.sh.in
--- a/src/lib/log/tests/destination_test.sh.in
+++ b/src/lib/log/tests/destination_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2011-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -7,22 +8,29 @@
 
 # Checks that the logger will route messages to the chosen destination.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
+
 testname="Destination test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-tempfile=@abs_builddir@/destination_test_tempfile_$$
-destfile1_tmp=@abs_builddir@/destination_test_destfile_1_tmp_$$
-destfile2_tmp=@abs_builddir@/destination_test_destfile_2_tmp_$$
-destfile1=@abs_builddir@/destination_test_destfile_1_$$
-destfile2=@abs_builddir@/destination_test_destfile_2_$$
+tempfile="@abs_builddir@/destination_test_tempfile_$$"
+destfile1_tmp="@abs_builddir@/destination_test_destfile_1_tmp_$$"
+destfile2_tmp="@abs_builddir@/destination_test_destfile_2_tmp_$$"
+destfile1="@abs_builddir@/destination_test_destfile_1_$$"
+destfile2="@abs_builddir@/destination_test_destfile_2_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
@@ -41,19 +49,18 @@ sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1
 sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile2_tmp > $destfile2
 # strip the thread ids
 
-
-echo -n  "   - destination 1:"
+printf '   - destination 1:'
 cut -d' ' -f3- $destfile1 | diff $tempfile -
 passfail $?
 
-echo -n  "   - destination 2:"
+printf '   - destination 2:'
 cut -d' ' -f3- $destfile2 | diff $tempfile -
 passfail $?
 
 # Tidy up.
 rm -f $tempfile $destfile1_tmp $destfile2_tmp $destfile1 $destfile2
 
-echo     "2. Two loggers, different destinations and severities"
+printf '2. Two loggers, different destinations and severities\n'
 rm -f $destfile1 $destfile2
 ./logger_example -l example -s info -f $destfile1_tmp -l alpha -s warn -f $destfile2_tmp
 
@@ -73,17 +80,16 @@ ERROR [example.beta] LOG_BAD_DESTINATION unrecognized log destination: beta_erro
 WARN  [example.beta] LOG_BAD_STREAM bad log console output stream: beta_warn
 INFO  [example.beta] LOG_READ_ERROR error reading from message file beta: info
 .
-echo -n  "   - destination 1:"
+printf '   - destination 1:'
 cut -d' ' -f3- $destfile1 | diff $tempfile -
 passfail $?
 
-echo -n  "   - destination 2:"
+printf '   - destination 2:'
 cat > $tempfile << .
 WARN  [example.alpha] LOG_READ_ERROR error reading from message file a.txt: dummy reason
 .
 cut -d' ' -f3- $destfile2 | diff $tempfile -
 passfail $?
-
 if [ $failcount -eq 0 ]; then
     echo "PASS: $testname"
 elif [ $failcount -eq 1 ]; then
diff --git a/src/lib/log/tests/init_logger_test.sh.in b/src/lib/log/tests/init_logger_test.sh.in
--- a/src/lib/log/tests/init_logger_test.sh.in
+++ b/src/lib/log/tests/init_logger_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2011-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -8,26 +9,34 @@
 # Checks that the initLogger() call uses for unit tests respects the setting of
 # the environment variables.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
+
 testname="initLogger test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-tempfile=@abs_builddir@/init_logger_test_tempfile_$$
-destfile_tmp=@abs_builddir@/init_logger_test_destfile_tmp_$$
-destfile=@abs_builddir@/init_logger_test_destfile_$$
+tempfile="@abs_builddir@/init_logger_test_tempfile_$$"
+destfile_tmp="@abs_builddir@/init_logger_test_destfile_tmp_$$"
+destfile="@abs_builddir@/init_logger_test_destfile_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
-echo "1. Checking that KEA_LOGGER_SEVERITY/KEA_LOGGER_DBGLEVEL work"
+printf '1. Checking that KEA_LOGGER_SEVERITY/KEA_LOGGER_DBGLEVEL work\n'
 
-echo -n  "   - severity=DEBUG, dbglevel=99: "
+set +e
+printf '   - severity=DEBUG, dbglevel=99: '
 cat > $tempfile << .
 DEBUG [kea.log] LOG_BAD_DESTINATION unrecognized log destination: debug-0
 DEBUG [kea.log] LOG_BAD_DESTINATION unrecognized log destination: debug-50
@@ -42,7 +51,7 @@ KEA_LOGGER_DESTINATION=stdout KEA_LOGGER_SEVERITY=DEBUG KEA_LOGGER_DBGLEVEL=99 .
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n  "   - severity=DEBUG, dbglevel=50: "
+printf '   - severity=DEBUG, dbglevel=50: '
 cat > $tempfile << .
 DEBUG [kea.log] LOG_BAD_DESTINATION unrecognized log destination: debug-0
 DEBUG [kea.log] LOG_BAD_DESTINATION unrecognized log destination: debug-50
@@ -56,7 +65,7 @@ KEA_LOGGER_DESTINATION=stdout KEA_LOGGER_SEVERITY=DEBUG KEA_LOGGER_DBGLEVEL=50 .
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n  "   - severity=WARN: "
+printf '   - severity=WARN: '
 cat > $tempfile << .
 WARN  [kea.log] LOG_BAD_STREAM bad log console output stream: warn
 ERROR [kea.log] LOG_DUPLICATE_MESSAGE_ID duplicate message ID (error) in compiled code
@@ -67,9 +76,9 @@ KEA_LOGGER_DESTINATION=stdout KEA_LOGGER_SEVERITY=WARN ./init_logger_test | \
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo "2. Checking that KEA_LOGGER_DESTINATION works"
+printf '2. Checking that KEA_LOGGER_DESTINATION works\n'
 
-echo -n  "   - stdout: "
+printf '   - stdout: '
 cat > $tempfile << .
 FATAL [kea.log] LOG_NO_MESSAGE_ID line fatal: message definition line found without a message ID
 .
@@ -79,14 +88,14 @@ sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1
 cut -d' ' -f3- $destfile | diff $tempfile -
 passfail $?
 
-echo -n  "   - stderr: "
+printf '   - stderr: '
 rm -f $destfile_tmp $destfile
 KEA_LOGGER_SEVERITY=FATAL KEA_LOGGER_DESTINATION=stderr ./init_logger_test 2> $destfile_tmp
 sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile_tmp > $destfile
 cut -d' ' -f3- $destfile | diff $tempfile -
 passfail $?
 
-echo -n  "   - file: "
+printf '   - file: '
 rm -f $destfile_tmp $destfile
 KEA_LOGGER_SEVERITY=FATAL KEA_LOGGER_DESTINATION=$destfile_tmp ./init_logger_test
 sed -e 's/\[\([a-z0-9\.]\{1,\}\)\/\([0-9]\{1,\}\)\.\(0x\)\{0,1\}\([0-9A-Fa-f]\{1,\}\)\]/[\1]/' < $destfile_tmp > $destfile
@@ -96,11 +105,11 @@ passfail $?
 # Note: can't automatically test syslog output.
 
 if [ $failcount -eq 0 ]; then
-    echo "PASS: $testname"
+    printf 'PASS: %s\n' "${testname}"
 elif [ $failcount -eq 1 ]; then
-    echo "FAIL: $testname - 1 test failed"
+    printf 'FAIL: %s - 1 test failed\n' "${testname}"
 else
-    echo "FAIL: $testname - $failcount tests failed"
+    printf 'FAIL: %s - %s tests failed\n' "${testname}" "${failcount}"
 fi
 
 # Tidy up.
diff --git a/src/lib/log/tests/local_file_test.sh.in b/src/lib/log/tests/local_file_test.sh.in
--- a/src/lib/log/tests/local_file_test.sh.in
+++ b/src/lib/log/tests/local_file_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2011-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -8,19 +9,26 @@
 # Checks that a local message file can override the definitions in the message
 # dictionary.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
+
 testname="Local message file test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-localmes=@abs_builddir@/localdef_mes_$$
-tempfile=@abs_builddir@/run_time_init_test_tempfile_$$
+localmes="@abs_builddir@/localdef_mes_$$"
+tempfile="@abs_builddir@/run_time_init_test_tempfile_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
@@ -32,7 +40,7 @@ cat > $localmes << .
 % LOG_READING_LOCAL_FILE replacement read local message file, parameter is '%1'
 .
 
-echo -n "1. Local message replacement:"
+printf '1. Local message replacement:'
 cat > $tempfile << .
 WARN  [example.log] LOG_NO_SUCH_MESSAGE could not replace message text for 'LOG_NOTHERE': no such message
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
@@ -48,7 +56,7 @@ WARN  [example.beta] LOG_BAD_STREAM bad log console output stream: beta_warn
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n "2. Report error if unable to read local message file:"
+printf '2. Report error if unable to read local message file:'
 cat > $tempfile << .
 ERROR [example.log] LOG_INPUT_OPEN_FAIL unable to open message file $localmes for input: No such file or directory
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
@@ -66,11 +74,11 @@ rm -f $localmes
 passfail $?
 
 if [ $failcount -eq 0 ]; then
-    echo "PASS: $testname"
+    printf 'PASS: %s\n' "$testname"
 elif [ $failcount -eq 1 ]; then
-    echo "FAIL: $testname - 1 test failed"
+    printf 'FAIL: %s - 1 test failed\n' "$testname"
 else
-    echo "FAIL: $testname - $failcount tests failed"
+    printf 'FAIL: %s - %s tests failed\n' "$testname" "$failcount"
 fi
 
 # Tidy up.
diff --git a/src/lib/log/tests/logger_lock_test.sh.in b/src/lib/log/tests/logger_lock_test.sh.in
--- a/src/lib/log/tests/logger_lock_test.sh.in
+++ b/src/lib/log/tests/logger_lock_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2012-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -8,20 +9,27 @@
 # Checks that the locker interprocess sync locks are acquired and
 # released correctly.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
+
 failcount=0
-tempfile=@abs_builddir@/logger_lock_test_tempfile_$$
-destfile=@abs_builddir@/logger_lock_test_destfile_$$
+tempfile="@abs_builddir@/logger_lock_test_tempfile_$$"
+destfile="@abs_builddir@/logger_lock_test_destfile_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
-echo -n  "Testing that logger acquires and releases locks correctly:"
+printf 'Testing that logger acquires and releases locks correctly:'
 cat > $tempfile << .
 LOGGER_LOCK_TEST: MUTEXLOCK
 LOGGER_LOCK_TEST: LOCK
diff --git a/src/lib/log/tests/severity_test.sh.in b/src/lib/log/tests/severity_test.sh.in
--- a/src/lib/log/tests/severity_test.sh.in
+++ b/src/lib/log/tests/severity_test.sh.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 # Copyright (C) 2011-2020 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -8,22 +9,29 @@
 # Checks that the logger will limit the output of messages less severe than
 # the severity/debug setting.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# Allow non-zero exit codes to be explicitly checked in this test.
+set +e
+
 testname="Severity test"
-echo $testname
+printf '%s\n' "${testname}"
 
 failcount=0
-tempfile=@abs_builddir@/severity_test_tempfile_$$
+tempfile="@abs_builddir@/severity_test_tempfile_$$"
 
 passfail() {
-    if [ $1 -eq 0 ]; then
-        echo " pass"
+    if [ "${1}" -eq 0 ]; then
+        printf ' pass\n'
     else
-        echo " FAIL"
-        failcount=`expr $failcount + $1`
+        printf ' FAIL\n'
+        failcount=$((failcount + $1))
     fi
 }
 
-echo -n "1. Default parameters:"
+printf '1. Default parameters:'
 cat > $tempfile << .
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
 ERROR [example] LOG_READING_LOCAL_FILE reading local message file dummy/file
@@ -40,7 +48,7 @@ INFO  [example.beta] LOG_READ_ERROR error reading from message file beta: info
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n "2. Severity filter:"
+printf '2. Severity filter:'
 cat > $tempfile << .
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
 ERROR [example] LOG_READING_LOCAL_FILE reading local message file dummy/file
@@ -52,7 +60,7 @@ ERROR [example.beta] LOG_BAD_DESTINATION unrecognized log destination: beta_erro
     cut -d' ' -f3- | diff $tempfile -
 passfail $?
 
-echo -n "3. Debug level:"
+printf '3. Debug level:'
 cat > $tempfile << .
 FATAL [example] LOG_WRITE_ERROR error writing to test1: 42
 ERROR [example] LOG_READING_LOCAL_FILE reading local message file dummy/file
@@ -74,11 +82,11 @@ DEBUG [example.beta] LOG_BAD_SEVERITY unrecognized log severity: beta/25
 passfail $?
 
 if [ $failcount -eq 0 ]; then
-    echo "PASS: $testname"
+    printf 'PASS: %s\n' "$testname"
 elif [ $failcount -eq 1 ]; then
-    echo "FAIL: $testname - 1 test failed"
+    printf 'FAIL: %s - 1 test failed\n' "$testname"
 else
-    echo "FAIL: $testname - $failcount tests failed"
+    printf 'FAIL: %s - %s tests failed\n' "$testname" "$failcount"
 fi
 
 # Tidy up
diff --git a/src/lib/util/tests/process_spawn_app.sh.in b/src/lib/util/tests/process_spawn_app.sh.in
--- a/src/lib/util/tests/process_spawn_app.sh.in
+++ b/src/lib/util/tests/process_spawn_app.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-#
+
 # Copyright (C) 2015-2016 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
@@ -24,14 +24,18 @@
 # test has much enough time to verify that the convenience methods
 # checking the state of the process, i.e. process running or not.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 exit_code=
 
-while [ ! -z "${1}" ]
+while [ -n "${1+x}" ]
 do
     option=${1}
     case ${option} in
         -p)
-            exit_code=$$
+            exit_code=${$}
             ;;
         -e)
             shift
@@ -39,7 +43,7 @@ do
             ;;
         -s)
             shift
-            sleep ${1}
+            sleep "${1}"
             ;;
         *)
             exit 123
@@ -51,7 +55,7 @@ done
 # The exit code of 32 is returned when no args specified or
 # when only the -s arg has been specified.
 if [ -z "${exit_code}" ]; then
-    exit 32;
+    exit 32
 fi
 
-exit ${exit_code}
+exit "${exit_code}"
diff --git a/src/share/database/scripts/cql/upgrade_3.0_to_4.0.sh.in b/src/share/database/scripts/cql/upgrade_3.0_to_4.0.sh.in
--- a/src/share/database/scripts/cql/upgrade_3.0_to_4.0.sh.in
+++ b/src/share/database/scripts/cql/upgrade_3.0_to_4.0.sh.in
@@ -1,12 +1,31 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2019-2020 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, arrays are undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh" ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
 # Need a path for temporary files created during upgrade data migration
@@ -18,11 +37,12 @@ else
     temp_file_dir="@abs_top_builddir@/src/share/database/scripts/cql"
 fi
 
-cqlargs=$@
+# Save the command line arguments for later use.
+cqlargs=("${@}")
 
 # Ensures the current schema version is 3.0. If not it exits.
 check_version() {
-    version=$(cql_version $cqlargs)
+    version=$(cql_version "${cqlargs[@]}")
 
     if [ "${version}" != "3.0" ]; then
         printf "This script upgrades 3.0 to 4.0. Reported version is %s. Skipping upgrade.\n" "${version}"
@@ -32,7 +52,7 @@ check_version() {
 
 # Peforms the schema changes from 3.0 to 4.0
 update_schema() {
-    cqlsh $cqlargs <<EOF
+    cqlsh "${cqlargs[@]}" <<EOF
 -- This line starts database upgrade to version 4.0
 
 -- -----------------------------------------------------
@@ -81,17 +101,11 @@ CREATE INDEX IF NOT EXISTS hostsindex5 ON hosts (host_ipv4_address);
 CREATE INDEX IF NOT EXISTS hostsindex6 ON hosts (reserved_ipv6_prefix_address);
 CREATE INDEX IF NOT EXISTS hostsindex7 ON hosts (reserved_ipv6_prefix_length);
 EOF
-
-    if [ "$?" -ne 0 ]
-    then
-        echo Schema udpate FAILED!
-        exit 1
-    fi
 }
 
 # Peforms the clean up schema changes from 3.0 to 4.0
 clean_up_schema() {
-    cqlsh $cqlargs <<EOF
+    cqlsh "${cqlargs[@]}" <<EOF
 DROP TABLE IF EXISTS host_reservations;
 
 DROP INDEX IF EXISTS host_reservationsindex1;
@@ -108,12 +122,6 @@ INSERT INTO schema_version (version, minor) VALUES(4, 0);
 
 -- This line concludes database upgrade to version 4.0
 EOF
-
-    if [ "$?" -ne 0 ]
-    then
-        echo Schema udpate FAILED!
-        exit 1
-    fi
 }
 
 # Function to delete temporary migration files
@@ -121,12 +129,12 @@ clean_up() {
     # clean up the files
     if [ -e "$export_file" ]
     then
-        rm $export_file
+        rm "$export_file"
     fi
 
     if [ -e "$update_file" ]
     then
-        rm $update_file
+        rm "$update_file"
     fi
 }
 
@@ -150,48 +158,35 @@ exit_now() {
         echo "Data Migration FAILURE! $explanation"
     fi
 
-    exit $status
+    exit "$status"
 }
 
+# Prefix ${string} with ${count} characters like the one spciefied in
+# ${fill_char}.
 fill() {
     string=$1;shift
     count=$1;shift
     fill_char=$1;shift
-    length=`echo $string | wc -c`
-    length=$((length - 1))
-    if [ $length -gt $count ]; then
-        value=`echo "$string" | cut -c 1-$count`
-        return
-    fi
-    result=""
-    count=$((count - length))
-    i=1
-    while [ $i -le $count ]; do
-        result="$fill_char$result"
-        i=$((i+1))
-    done
-    value="$result$string"
+    value="$(printf "%${count}s" | sed "s/ /${fill_char}/g")${string}"
 }
 
 identifier_text() {
     string=$1;shift
-    length=`echo $string | wc -c`
-    length=$((length - 1))
+    length="${#string}"
     # skip 0x from 0xabcdef
-    string=`echo "$string" | cut -c 3-$length`
+    string=$(echo "$string" | cut -c "3-$length")
     identifier=""
     # add starting 0: 0xabc->0x0abc
     mod=$((length % 2))
     if [ $mod -ne 0 ]; then
         string="0"$string
     fi
-    length=`echo $string | wc -c`
-    length=$((length - 1))
+    length="${#string}"
     i=1
-    while [ $i -le $length ]; do
-        char=`echo "$string" | cut -c $i-$i`
+    while [ "$i" -le "$length" ]; do
+        char=$(echo "$string" | cut -c $i-$i)
         mod=$((i % 2))
-        if [ $mod -ne 0 -a $i -ne 1 ]; then
+        if test $mod -ne 0 && test $i -ne 1; then
             char=":"$char
         fi
         identifier=$identifier$char
@@ -201,15 +196,14 @@ identifier_text() {
 
 key_hash() {
     string=$1;shift
-    length=`echo $string | wc -c`
-    length=$((length - 1))
+    length="${#string}"
     FNV_prime=1099511628211
     FNV_offset_basis=-3750763034362895579 # signed value for 14695981039346656037
     hash=$FNV_offset_basis
     i=1
-    while [ $i -le $length ]; do
-        char=`echo "$string" | cut -c $i-$i`
-        data=`echo "$char" | tr -d "\n" | od -An -t uC | tr -d ' '`
+    while [ "$i" -le "$length" ]; do
+        char=$(echo "$string" | cut -c $i-$i)
+        data=$(echo "$char" | tr -d "\n" | od -An -t uC | tr -d ' ')
         hash=$((hash ^ data))
         hash=$((hash * FNV_prime))
         i=$((i+1))
@@ -226,7 +220,7 @@ generate_key() {
     key=""
     identifier_text "$host_identifier"
     local_host_identifier=$identifier
-    if [ ! -z $host_ipv4_address ] && [ $host_ipv4_address -eq 0 ]; then
+    if [ -n "$host_ipv4_address" ] && [ "$host_ipv4_address" -eq 0 ]; then
         fill "$local_host_identifier" 383 "-"
         key="$key$value"
         fill "$host_identifier_type" 10 "-"
@@ -277,8 +271,8 @@ migrate_host_data() {
          option_scope_id) \
         TO '$export_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -e "$query"
     then
         exit_now 1 "Cassandra export failed! Could not migrate data!"
     fi
@@ -286,7 +280,7 @@ migrate_host_data() {
     # Strip the carriage returns that CQL insists on adding.
     if [ -e "$export_file" ]
     then
-        cat $export_file | tr -d '\015' > $export_file.2
+        tr -d '\015' < "${export_file}" > $export_file.2
         mv $export_file.2 $export_file
     else
         # Shouldn't happen but then again we're talking about CQL here
@@ -296,12 +290,11 @@ migrate_host_data() {
     # Iterate through the exported data, accumulating update statements,
     # one for each reservation that needs updating.  We should have one
     # host per line.
-    line_cnt=0;
-    update_cnt=0;
-
+    line_cnt=0
+    update_cnt=0
     while read -r line
     do
-        line_cnt=$((line_cnt + 1));
+        line_cnt=$((line_cnt + 1))
         xIFS="$IFS"
         IFS=','
         i=1
@@ -338,8 +331,8 @@ migrate_host_data() {
         update_cnt=$((update_cnt + 1))
 
         IFS="$xIFS"
-        echo $line | sed -e "s/$host_id/$host_id,$key_data/" >> $update_file
-    done <  $export_file
+        echo "${line}" | sed -e "s/$host_id/$host_id,$key_data/" >> "${update_file}"
+    done < "${export_file}"
 
     # If we didn't record any updates, then hey, we're good to go!
     if [ "$update_cnt" -eq 0 ]
@@ -363,8 +356,7 @@ migrate_host_data() {
          option_scope_id) \
         FROM '$update_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+    if ! cqlsh "${cqlargs[@]}" -e "$query"
     then
         exit_now 1 "Cassandra updates failed"
     fi
@@ -373,5 +365,8 @@ migrate_host_data() {
 }
 
 check_version
-update_schema
+if ! update_schema; then
+    printf 'Schema update FAILED!\n'
+    exit 1
+fi
 migrate_host_data
diff --git a/src/share/database/scripts/cql/upgrade_4.0_to_5.0.sh.in b/src/share/database/scripts/cql/upgrade_4.0_to_5.0.sh.in
--- a/src/share/database/scripts/cql/upgrade_4.0_to_5.0.sh.in
+++ b/src/share/database/scripts/cql/upgrade_4.0_to_5.0.sh.in
@@ -1,13 +1,35 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2019-2020 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, arrays are undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh" ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
+
+# Save the command line arguments for later use.
+cqlargs=("${@}")
 
 # Need a path for temporary files created during data update
 # Use the state directory in the install path directory if it exists, otherwise
@@ -18,11 +40,9 @@ else
     temp_file_dir="@abs_top_builddir@/src/share/database/scripts/cql"
 fi
 
-cqlargs=$@
-
 # Ensures the current schema version is 4.0. If not it exits.
 check_version() {
-    version=$(cql_version $cqlargs)
+    version=$(cql_version "${cqlargs[@]}")
 
     if [ "${version}" != "4.0" ]; then
         printf "This script upgrades 4.0 to 5.0. Reported version is %s. Skipping upgrade.\n" "${version}"
@@ -32,7 +52,7 @@ check_version() {
 
 # Peforms the schema changes from 4.0 to 5.0
 update_schema() {
-    cqlsh $cqlargs <<EOF
+    cqlsh "${cqlargs[@]}" <<EOF
 -- This line starts database upgrade to version 5.0
 
 -- Add the lower case hostname column to reservations.
@@ -52,12 +72,6 @@ INSERT INTO schema_version (version, minor) VALUES(5, 0);
 
 -- This line concludes database upgrade to version 5.0
 EOF
-
-    if [ "$?" -ne 0 ]
-    then
-        echo Schema udpate FAILED!
-        exit 1
-    fi
 }
 
 # Functions to delete temporary update files
@@ -65,32 +79,32 @@ clean_up() {
     # clean up the files
     if [ -e "$host_export_file" ]
     then
-        rm $host_export_file
+        rm "$host_export_file"
     fi
 
     if [ -e "$host_update_file" ]
     then
-        rm $host_update_file
+        rm "$host_update_file"
     fi
 
     if [ -e "$lease4_export_file" ]
     then
-        rm $lease4_export_file
+        rm "$lease4_export_file"
     fi
 
     if [ -e "$lease4_update_file" ]
     then
-        rm $lease4_update_file
+        rm "$lease4_update_file"
     fi
 
     if [ -e "$lease6_export_file" ]
     then
-        rm $lease6_export_file
+        rm "$lease6_export_file"
     fi
 
     if [ -e "$lease6_update_file" ]
     then
-        rm $lease6_update_file
+        rm "$lease6_update_file"
     fi
 }
 
@@ -113,7 +127,7 @@ exit_now() {
         echo "Data Update FAILURE! $explanation"
     fi
 
-    exit $status
+    exit "$status"
 }
 
 # This function adds host 'lower_case_hostname' column.
@@ -129,8 +143,8 @@ update_host_data() {
     echo "Exporting hostnames to $host_export_file ..."
     query="COPY hosts (key, id, hostname) TO '$host_export_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -e "$query"
     then
         exit_now 1 "Cassandra get hostname failed! Could not update host!"
     fi
@@ -138,8 +152,8 @@ update_host_data() {
     # Strip the carriage returns that CQL insists on adding.
     if [ -e "$host_export_file" ]
     then
-        cat $host_export_file | tr -d '\015' > $host_export_file.2
-        mv $host_export_file.2 $host_export_file
+        tr -d '\015' < "$host_export_file" > "$host_export_file.2"
+        mv "$host_export_file.2" "$host_export_file"
     else
         # Shouldn't happen but then again we're talking about CQL here
         exit_now 1 "Cassandra export file $host_export_file is missing?"
@@ -148,14 +162,14 @@ update_host_data() {
     # Iterate through the exported data, accumulating update statements,
     # one for each reservation that needs updating.  We should have one
     # host per line.
-    line_cnt=0;
-    update_cnt=0;
+    line_cnt=0
+    update_cnt=0
 
     while read -r line
     do
-        line_cnt=$((line_cnt + 1));
+        line_cnt=$((line_cnt + 1))
         xIFS="$IFS"
-        IFS=$','
+        IFS=','
 
         i=1
         hostname=
@@ -189,13 +203,13 @@ update_host_data() {
         # If the hostname was not null set the lower case value
         if [ "$hostname" != "" ]
         then
-            lower=$(echo $hostname | tr '[:upper:]' '[:lower:]')
-            echo "update hosts set lower_case_hostname = '$lower' where key = $key and id = $host_id;" >> $host_update_file
+            lower=$(echo "${hostname}" | tr '[:upper:]' '[:lower:]')
+            echo "update hosts set lower_case_hostname = '$lower' where key = $key and id = $host_id;" >> "$host_update_file"
             update_cnt=$((update_cnt + 1))
         fi
 
         IFS="$xIFS"
-    done <  $host_export_file
+    done < "$host_export_file"
 
     # If we didn't record any updates, then hey, we're good to go!
     if [ "$update_cnt" -eq 0 ]
@@ -206,8 +220,8 @@ update_host_data() {
     # We have at least one update in the update file, so submit it # to cqlsh.
     echo "$update_cnt host update statements written to $host_update_file"
     echo "Running the updates..."
-    cqlsh $cqlargs -f "$host_update_file"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -f "$host_update_file"
     then
         exit_now 1 "Cassandra host updates failed"
     fi
@@ -228,8 +242,8 @@ update_lease4_data() {
     echo "Exporting hostnames to $lease4_export_file ..."
     query="COPY lease4 (address, hostname) TO '$lease4_export_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -e "$query"
     then
         exit_now 1 "Cassandra get hostname failed! Could not update lease4!"
     fi
@@ -237,8 +251,8 @@ update_lease4_data() {
     # Strip the carriage returns that CQL insists on adding.
     if [ -e "$lease4_export_file" ]
     then
-        cat $lease4_export_file | tr -d '\015' > $lease4_export_file.2
-        mv $lease4_export_file.2 $lease4_export_file
+        tr -d '\015' < "$lease4_export_file" > "$lease4_export_file.2"
+        mv "$lease4_export_file.2" "$lease4_export_file"
     else
         # Shouldn't happen but then again we're talking about CQL here
         exit_now 1 "Cassandra export file $lease4_export_file is missing?"
@@ -247,14 +261,14 @@ update_lease4_data() {
     # Iterate through the exported data, accumulating update statements,
     # one for each lease that needs updating.  We should have one lease4
     # per line.
-    line_cnt=0;
-    update_cnt=0;
+    line_cnt=0
+    update_cnt=0
 
     while read -r line
     do
-        line_cnt=$((line_cnt + 1));
+        line_cnt=$((line_cnt + 1))
         xIFS="$IFS"
-        IFS=$','
+        IFS=','
 
         i=1
         hostname=
@@ -285,13 +299,13 @@ update_lease4_data() {
         # If the hostname was not null set the lower case value
         if [ "$hostname" != "" ]
         then
-            lower=$(echo $hostname | tr '[:upper:]' '[:lower:]')
-            echo "update lease4 set hostname = '$lower' where address = $address;" >> $lease4_update_file
+            lower=$(echo "${hostname}" | tr '[:upper:]' '[:lower:]')
+            echo "update lease4 set hostname = '$lower' where address = $address;" >> "$lease4_update_file"
             update_cnt=$((update_cnt + 1))
         fi
 
         IFS="$xIFS"
-    done <  $lease4_export_file
+    done < "$lease4_export_file"
 
     # If we didn't record any updates, then hey, we're good to go!
     if [ "$update_cnt" -eq 0 ]
@@ -302,8 +316,8 @@ update_lease4_data() {
     # We have at least one update in the update file, so submit it # to cqlsh.
     echo "$update_cnt lease4 update statements written to $lease4_update_file"
     echo "Running the updates..."
-    cqlsh $cqlargs -f "$lease4_update_file"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -f "$lease4_update_file"
     then
         exit_now 1 "Cassandra lease4 updates failed"
     fi
@@ -324,8 +338,7 @@ update_lease6_data() {
     echo "Exporting hostnames to $lease6_export_file ..."
     query="COPY lease6 (address, hostname) TO '$lease6_export_file'"
 
-    cqlsh $cqlargs -e "$query"
-    if [ "$?" -ne 0 ]
+    if ! cqlsh "${cqlargs[@]}" -e "$query"
     then
         exit_now 1 "Cassandra get hostname failed! Could not update lease6!"
     fi
@@ -333,8 +346,8 @@ update_lease6_data() {
     # Strip the carriage returns that CQL insists on adding.
     if [ -e "$lease6_export_file" ]
     then
-        cat $lease6_export_file | tr -d '\015' > $lease6_export_file.2
-        mv $lease6_export_file.2 $lease6_export_file
+        tr -d '\015' < "$lease6_export_file" > "$lease6_export_file.2"
+        mv "$lease6_export_file.2" "$lease6_export_file"
     else
         # Shouldn't happen but then again we're talking about CQL here
         exit_now 1 "Cassandra export file $lease6_export_file is missing?"
@@ -343,14 +356,14 @@ update_lease6_data() {
     # Iterate through the exported data, accumulating update statements,
     # one for each lease that needs updating.  We should have one lease6
     # per line.
-    line_cnt=0;
-    update_cnt=0;
+    line_cnt=0
+    update_cnt=0
 
     while read -r line
     do
-        line_cnt=$((line_cnt + 1));
+        line_cnt=$((line_cnt + 1))
         xIFS="$IFS"
-        IFS=$','
+        IFS=','
 
         i=1
         hostname=
@@ -381,13 +394,13 @@ update_lease6_data() {
         # If the hostname was not null set the lower case value
         if [ "$hostname" != "" ]
         then
-            lower=$(echo $hostname | tr '[:upper:]' '[:lower:]')
-            echo "update lease6 set hostname = '$lower' where address = $address;" >> $lease6_update_file
+            lower=$(echo "${hostname}" | tr '[:upper:]' '[:lower:]')
+            echo "update lease6 set hostname = '$lower' where address = $address;" >> "$lease6_update_file"
             update_cnt=$((update_cnt + 1))
         fi
 
         IFS="$xIFS"
-    done <  $lease6_export_file
+    done < "$lease6_export_file"
 
     # If we didn't record any updates, then hey, we're good to go!
     if [ "$update_cnt" -eq 0 ]
@@ -398,8 +411,8 @@ update_lease6_data() {
     # We have at least one update in the update file, so submit it # to cqlsh.
     echo "$update_cnt lease6 update statements written to $lease6_update_file"
     echo "Running the updates..."
-    cqlsh $cqlargs -f "$lease6_update_file"
-    if [ "$?" -ne 0 ]
+
+    if ! cqlsh "${cqlargs[@]}" -f "$lease6_update_file"
     then
         exit_now 1 "Cassandra lease6 updates failed"
     fi
@@ -415,7 +428,10 @@ lease6_export_file="$temp_file_dir/cql_lease6_export.csv"
 lease6_update_file="$temp_file_dir/cql_lease6_update.cql"
 
 check_version
-update_schema
+if ! update_schema; then
+    printf 'Schema update FAILED!\n'
+    exit 1
+fi
 update_host_data
 update_lease4_data
 update_lease6_data
diff --git a/src/share/database/scripts/mysql/upgrade_8.1_to_8.2.sh.in b/src/share/database/scripts/mysql/upgrade_8.1_to_8.2.sh.in
--- a/src/share/database/scripts/mysql/upgrade_8.1_to_8.2.sh.in
+++ b/src/share/database/scripts/mysql/upgrade_8.1_to_8.2.sh.in
@@ -1,78 +1,88 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2019-2020 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# shellcheck disable=SC2039
+# SC2039: In POSIX sh, 'local' is undefined.
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
-VERSION=`mysql_version "$@"`
-
-# We need to set global RESULT when we exit. This is checked by callers.
-bail() {
-    RESULT=$1
-    exit $1
-}
+VERSION=$(mysql_version "$@")
 
 if [ "$VERSION" != "8.1" ]; then
-    printf "This script upgrades 8.1 to 8.2. Reported version is $VERSION. Skipping upgrade.\n"
-    bail 0
+    printf 'This script upgrades 8.1 to 8.2. '
+    printf 'Reported version is %s. Skipping upgrade.\n' "${VERSION}"
+    exit 0
 fi
 
 # Get the schema name from database argument. We need this to
 # query information_schema for the right database.
-for arg in $@
+for arg in "${@}"
 do
-    cnt=`echo $arg | grep -c "^\-\-"`
-    if [ $cnt -eq 0 ]
+    if ! grep -Eq '^\-\-' <<<"${arg}"
     then
         schema="$arg"
-        break;
+        break
     fi
 done
 
 # Make sure we can id the schema
-if [ -z $schema ]
+if [ -z "$schema" ]
 then
-    printf "Could not find database schema name in cmd line args: $@\n"
-    bail 255
+    printf "Could not find database schema name in cmd line args: %s\n" "${*}"
+    exit 255
 fi
 
-# Save the command line args, as we use these later change_column function. 
-cmdargs="$@"
+# Save the command line args, as we use these later change_column function.
+cmdargs=("${@}")
 
 # Function to rename a column in a table.
 change_column() {
-    local schema="$1"
-    local table="$2"
-    local ocolumn="$3"
-    local ncolumn="$4"
+    local schema="${1-}"
+    local table="${2-}"
+    local ocolumn="${3-}"
+    local ncolumn="${4-}"
 
     # First let's find out if the column name in the table actually needs updating.
     sql="select count(column_name) from information_schema.columns where table_schema='$schema' and table_name = '$table' and column_name = '$ocolumn'"
-
-    count=`mysql -N -B $cmdargs -e "$sql"`
-    if [ $? -ne 0 ]
+    if ! count=$(mysql -N -B "${cmdargs[@]}" -e "$sql")
     then
-        printf "change_column: schema query failed [$sql]\n"
-        bail 255;
+        printf 'change_column: schema query failed [%s]\n' "${sql}"
+        exit 255
     fi
 
-    # If we found a match record, the column needs to be renamed 
+    # If we found a match record, the column needs to be renamed
     if [ "$count" -eq 1 ]
     then
         sql="ALTER TABLE $table CHANGE COLUMN $ocolumn $ncolumn"
-        mysql -N -B $cmdargs -e "$sql"
-        if [ $? -ne 0 ]
+        if ! mysql -N -B "${cmdargs[@]}" -e "$sql"
         then
-            printf "change_column: alter query failed: [$sql]\n"
-            bail 255;
+            printf 'change_column: alter query failed [%s]\n' "${sql}"
+            exit 255
         fi
     else
-        printf "$table column is already correct\n"
+        printf '%s column is already correct\n' "${table}"
     fi
 }
 
@@ -485,15 +495,7 @@ SET version = '8', minor = '2';
 
 EOF
 
-RESULT=$?
-if [ $RESULT -ne 0 ]
-then
-    exit $RESULT
-fi
-
 # We need to rename the columns in the option def tables because "array" is
 # a MySQL keyword as of 8.0.17
-change_column $schema dhcp4_option_def array "is_array TINYINT(1) NOT NULL"
-change_column $schema dhcp6_option_def array "is_array TINYINT(1) NOT NULL"
-
-bail 0
+change_column "${schema}" dhcp4_option_def array "is_array TINYINT(1) NOT NULL"
+change_column "${schema}" dhcp6_option_def array "is_array TINYINT(1) NOT NULL"
diff --git a/src/share/database/scripts/mysql/upgrade_9.4_to_9.5.sh.in b/src/share/database/scripts/mysql/upgrade_9.4_to_9.5.sh.in
--- a/src/share/database/scripts/mysql/upgrade_9.4_to_9.5.sh.in
+++ b/src/share/database/scripts/mysql/upgrade_9.4_to_9.5.sh.in
@@ -1,18 +1,35 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2020 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
-VERSION=`mysql_version "$@"`
+VERSION=$(mysql_version "$@")
 
 if [ "$VERSION" != "9.4" ]; then
-    printf "This script upgrades 9.4 to 9.5. Reported version is $VERSION. Skipping upgrade.\n"
+    printf 'This script upgrades 9.4 to 9.5. '
+    printf 'Reported version is %s. Skipping upgrade.\n' "${VERSION}"
     exit 0
 fi
 
@@ -151,7 +168,3 @@ SET version = '9', minor = '5';
 # This line concludes database upgrade to version 9.5.
 
 EOF
-
-RESULT=$?
-
-exit $?
diff --git a/src/share/database/scripts/pgsql/upgrade_2.0_to_3.0.sh.in b/src/share/database/scripts/pgsql/upgrade_2.0_to_3.0.sh.in
--- a/src/share/database/scripts/pgsql/upgrade_2.0_to_3.0.sh.in
+++ b/src/share/database/scripts/pgsql/upgrade_2.0_to_3.0.sh.in
@@ -1,18 +1,35 @@
 #!/bin/sh
 
-prefix=@prefix@
+# Copyright (C) 2016-2020 Internet Systems Consortium, Inc. ("ISC")
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
-VERSION=`pgsql_version "$@"`
+VERSION=$(pgsql_version "$@")
 
 if [ "$VERSION" != "2.0" ]; then
-    printf "This script upgrades 2.0 to 3.0. Reported version is $VERSION. Skipping upgrade.\n"
+    printf 'This script upgrades 2.0 to 3.0. '
+    printf 'Reported version is %s. Skipping upgrade.\n' "${VERSION}"
     exit 0
 fi
 
@@ -274,5 +291,3 @@ UPDATE schema_version
 COMMIT;
 
 EOF
-
-exit $RESULT
diff --git a/src/share/database/scripts/pgsql/wipe_data.sh.in b/src/share/database/scripts/pgsql/wipe_data.sh.in
--- a/src/share/database/scripts/pgsql/wipe_data.sh.in
+++ b/src/share/database/scripts/pgsql/wipe_data.sh.in
@@ -12,30 +12,41 @@
 # including leases, reservations, etc... Use at your own peril.
 # Reference tables will be left in-tact.
 
-prefix=@prefix@
+# shellcheck disable=SC1091
+# SC1091: Not following: ... was not specified as input (see shellcheck -x).
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+prefix="@prefix@"
+
 # Include utilities. Use installed version if available and
 # use build version if it isn't.
 if [ -e @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh ]; then
-    . @datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh
+    . "@datarootdir@/@PACKAGE_NAME@/scripts/admin-utils.sh"
 else
-    . @abs_top_builddir@/src/bin/admin/admin-utils.sh
+    . "@abs_top_builddir@/src/bin/admin/admin-utils.sh"
 fi
 
 # First argument is must be the expected schema version <major>.<minor>
 exp_version="$1"
-shift;
+shift
 
 # Remaining arguments are used as pgsql command line arguments
 
 # If the existing schema doesn't match, the fail
-VERSION=`pgsql_version "$@"`
+VERSION=$(pgsql_version "$@")
 if [ "$VERSION" = "" ]; then
     printf "Cannot wipe data, schema version could not be detected.\n"
     exit 1
 fi
 
 if [ "$VERSION" != "$exp_version" ]; then
-    printf "Cannot wipe data, wrong schema version. Expected $exp_version, found version $VERSION.\n"
+    printf 'Cannot wipe data, wrong schema version. '
+    printf 'Expected version %s, found %s.\n' "${exp_version}" "${VERSION}"
     exit 1
 fi
 
@@ -55,7 +66,3 @@ DELETE FROM lease6_stat;
 DELETE FROM logs;
 COMMIT;
 EOF
-
-RESULT=$?
-
-exit $RESULT
diff --git a/tools/path_replacer.sh.in b/tools/path_replacer.sh.in
--- a/tools/path_replacer.sh.in
+++ b/tools/path_replacer.sh.in
@@ -1,10 +1,11 @@
 #!/bin/sh
+
 # Copyright (C) 2014-2019 Internet Systems Consortium, Inc. ("ISC")
 #
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
-#
+
 # This script replaces @prefix@, @localstatedir@ and other automake/autoconf
 # variables with their actual content.
 #
@@ -14,13 +15,19 @@
 #
 # This script is initially used to generate configuration files, but it is
 # generic and can be used to generate any text files.
-#
 
-prefix=@prefix@
-sysconfdir=@sysconfdir@
-localstatedir=@localstatedir@
-exec_prefix=@exec_prefix@
-libdir=@libdir@
+# shellcheck disable=SC2034
+# SC2034: ... appears unused. Verify use (or export if used externally).
+
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
+prefix="@prefix@"
+sysconfdir="@sysconfdir@"
+localstatedir="@localstatedir@"
+exec_prefix="@exec_prefix@"
+libdir="@libdir@"
 
 echo "Replacing \@prefix\@ with ${prefix}"
 echo "Replacing \@libdir\@ with ${libdir}"
@@ -30,4 +37,4 @@ echo "Replacing \@localstatedir\@ with ${localstatedir}"
 echo "Input file: $1"
 echo "Output file: $2"
 
-sed -e "s@SEP@\@libdir\@@SEP@${libdir}@SEP@g; s@SEP@\@localstatedir\@@SEP@${localstatedir}@SEP@g; s@SEP@\@prefix\@@SEP@${prefix}@SEP@g; s@SEP@\@sysconfdir\@@SEP@${sysconfdir}@SEP@g" $1 > $2
+sed -e "s@SEP@\@libdir\@@SEP@${libdir}@SEP@g; s@SEP@\@localstatedir\@@SEP@${localstatedir}@SEP@g; s@SEP@\@prefix\@@SEP@${prefix}@SEP@g; s@SEP@\@sysconfdir\@@SEP@${sysconfdir}@SEP@g" "${1}" > "${2}"
diff --git a/tools/sysrepo_config b/tools/sysrepo_config
--- a/tools/sysrepo_config
+++ b/tools/sysrepo_config
@@ -10,6 +10,10 @@
 # This script is used to run Kea from installation directory,
 # as well as for running tests.
 
+# Exit with error if commands exit with non-zero and if undefined variables are
+# used.
+set -eu
+
 if [ "$(uname -s)" = "Darwin" ]; then
     DIR=$(stat -f %N "$0" | xargs dirname)
 else
